// Generated by scripts/photo-samples.mjs. Do not edit by hand.
import type { SampleId } from './fixtures';

export interface PhotoBox {
  page: number;
  x: number;
  y: number;
  w: number;
  h: number;
}

export interface SamplePhoto {
  pages: { src: string; width: number; height: number }[];
  /** Where each document line sits on its page, in the page's own pixels. */
  lines: Record<string, PhotoBox>;
}

export const SAMPLE_PHOTOS: Record<SampleId, SamplePhoto> = {
  "fd-note-clean": {
    "pages": [
      {
        "src": "/photo-samples/fd-note-clean-1.jpg",
        "width": 900,
        "height": 1200
      }
    ],
    "lines": {
      "c1": {
        "page": 1,
        "x": 97,
        "y": 230,
        "w": 689,
        "h": 47
      },
      "c2": {
        "page": 1,
        "x": 98,
        "y": 260,
        "w": 689,
        "h": 46
      },
      "c3": {
        "page": 1,
        "x": 99,
        "y": 289,
        "w": 689,
        "h": 46
      },
      "c4": {
        "page": 1,
        "x": 100,
        "y": 319,
        "w": 689,
        "h": 46
      },
      "c5": {
        "page": 1,
        "x": 100,
        "y": 348,
        "w": 689,
        "h": 46
      },
      "c6": {
        "page": 1,
        "x": 101,
        "y": 378,
        "w": 689,
        "h": 46
      },
      "c7": {
        "page": 1,
        "x": 102,
        "y": 407,
        "w": 689,
        "h": 46
      },
      "c8": {
        "page": 1,
        "x": 102,
        "y": 437,
        "w": 689,
        "h": 46
      },
      "c9": {
        "page": 1,
        "x": 103,
        "y": 466,
        "w": 689,
        "h": 46
      },
      "c10": {
        "page": 1,
        "x": 104,
        "y": 496,
        "w": 689,
        "h": 46
      },
      "c11": {
        "page": 1,
        "x": 105,
        "y": 525,
        "w": 689,
        "h": 46
      },
      "c12": {
        "page": 1,
        "x": 105,
        "y": 555,
        "w": 689,
        "h": 46
      }
    }
  },
  "fd-note": {
    "pages": [
      {
        "src": "/photo-samples/fd-note-1.jpg",
        "width": 900,
        "height": 1200
      },
      {
        "src": "/photo-samples/fd-note-2.jpg",
        "width": 900,
        "height": 1200
      }
    ],
    "lines": {
      "n1": {
        "page": 1,
        "x": 97,
        "y": 230,
        "w": 689,
        "h": 47
      },
      "n2": {
        "page": 1,
        "x": 98,
        "y": 260,
        "w": 689,
        "h": 46
      },
      "n3": {
        "page": 1,
        "x": 99,
        "y": 289,
        "w": 689,
        "h": 46
      },
      "n4": {
        "page": 1,
        "x": 100,
        "y": 319,
        "w": 689,
        "h": 46
      },
      "n5": {
        "page": 1,
        "x": 100,
        "y": 348,
        "w": 689,
        "h": 46
      },
      "n6": {
        "page": 1,
        "x": 101,
        "y": 378,
        "w": 689,
        "h": 46
      },
      "n7": {
        "page": 1,
        "x": 102,
        "y": 407,
        "w": 689,
        "h": 46
      },
      "n8": {
        "page": 1,
        "x": 102,
        "y": 437,
        "w": 689,
        "h": 46
      },
      "n9": {
        "page": 1,
        "x": 103,
        "y": 466,
        "w": 689,
        "h": 46
      },
      "n10": {
        "page": 1,
        "x": 104,
        "y": 496,
        "w": 689,
        "h": 46
      },
      "n11": {
        "page": 1,
        "x": 105,
        "y": 525,
        "w": 689,
        "h": 46
      },
      "n12": {
        "page": 1,
        "x": 105,
        "y": 555,
        "w": 689,
        "h": 46
      },
      "n13": {
        "page": 1,
        "x": 106,
        "y": 584,
        "w": 689,
        "h": 46
      },
      "n14": {
        "page": 1,
        "x": 107,
        "y": 614,
        "w": 689,
        "h": 46
      },
      "n15": {
        "page": 1,
        "x": 107,
        "y": 643,
        "w": 689,
        "h": 46
      },
      "n16": {
        "page": 1,
        "x": 108,
        "y": 673,
        "w": 689,
        "h": 46
      },
      "n17": {
        "page": 1,
        "x": 109,
        "y": 702,
        "w": 689,
        "h": 46
      },
      "n18": {
        "page": 1,
        "x": 110,
        "y": 732,
        "w": 689,
        "h": 46
      },
      "n19": {
        "page": 1,
        "x": 110,
        "y": 761,
        "w": 689,
        "h": 46
      },
      "n20": {
        "page": 1,
        "x": 111,
        "y": 791,
        "w": 689,
        "h": 46
      },
      "n21": {
        "page": 1,
        "x": 112,
        "y": 820,
        "w": 689,
        "h": 46
      },
      "n22": {
        "page": 1,
        "x": 113,
        "y": 850,
        "w": 689,
        "h": 46
      },
      "n23": {
        "page": 2,
        "x": 97,
        "y": 230,
        "w": 689,
        "h": 47
      },
      "n24": {
        "page": 2,
        "x": 98,
        "y": 260,
        "w": 689,
        "h": 46
      },
      "n25": {
        "page": 2,
        "x": 99,
        "y": 289,
        "w": 689,
        "h": 46
      },
      "n26": {
        "page": 2,
        "x": 100,
        "y": 319,
        "w": 689,
        "h": 46
      },
      "n27": {
        "page": 2,
        "x": 100,
        "y": 348,
        "w": 689,
        "h": 46
      },
      "n28": {
        "page": 2,
        "x": 101,
        "y": 378,
        "w": 689,
        "h": 46
      },
      "n29": {
        "page": 2,
        "x": 102,
        "y": 407,
        "w": 689,
        "h": 46
      },
      "n30": {
        "page": 2,
        "x": 102,
        "y": 437,
        "w": 689,
        "h": 46
      },
      "n31": {
        "page": 2,
        "x": 103,
        "y": 466,
        "w": 689,
        "h": 46
      },
      "n32": {
        "page": 2,
        "x": 104,
        "y": 496,
        "w": 689,
        "h": 46
      },
      "n33": {
        "page": 2,
        "x": 105,
        "y": 525,
        "w": 689,
        "h": 46
      },
      "n34": {
        "page": 2,
        "x": 105,
        "y": 555,
        "w": 689,
        "h": 46
      },
      "n35": {
        "page": 2,
        "x": 106,
        "y": 584,
        "w": 689,
        "h": 46
      },
      "n36": {
        "page": 2,
        "x": 107,
        "y": 614,
        "w": 689,
        "h": 46
      },
      "n37": {
        "page": 2,
        "x": 107,
        "y": 643,
        "w": 689,
        "h": 46
      },
      "n38": {
        "page": 2,
        "x": 108,
        "y": 673,
        "w": 689,
        "h": 46
      },
      "n39": {
        "page": 2,
        "x": 109,
        "y": 702,
        "w": 689,
        "h": 46
      },
      "n40": {
        "page": 2,
        "x": 110,
        "y": 732,
        "w": 689,
        "h": 46
      }
    }
  },
  "fd-invoice": {
    "pages": [
      {
        "src": "/photo-samples/fd-invoice-1.jpg",
        "width": 900,
        "height": 1200
      },
      {
        "src": "/photo-samples/fd-invoice-2.jpg",
        "width": 900,
        "height": 1200
      }
    ],
    "lines": {
      "f1": {
        "page": 1,
        "x": 126,
        "y": 253,
        "w": 661,
        "h": 48
      },
      "f2": {
        "page": 1,
        "x": 125,
        "y": 289,
        "w": 661,
        "h": 48
      },
      "f3": {
        "page": 1,
        "x": 124,
        "y": 324,
        "w": 661,
        "h": 48
      },
      "f4": {
        "page": 1,
        "x": 124,
        "y": 359,
        "w": 661,
        "h": 48
      },
      "f5": {
        "page": 1,
        "x": 123,
        "y": 394,
        "w": 661,
        "h": 48
      },
      "f6": {
        "page": 1,
        "x": 122,
        "y": 429,
        "w": 661,
        "h": 48
      },
      "f7": {
        "page": 1,
        "x": 122,
        "y": 464,
        "w": 661,
        "h": 48
      },
      "f8": {
        "page": 2,
        "x": 126,
        "y": 253,
        "w": 661,
        "h": 48
      },
      "f9": {
        "page": 2,
        "x": 125,
        "y": 289,
        "w": 661,
        "h": 48
      },
      "f10": {
        "page": 2,
        "x": 124,
        "y": 324,
        "w": 661,
        "h": 48
      },
      "f11": {
        "page": 2,
        "x": 124,
        "y": 359,
        "w": 661,
        "h": 48
      },
      "f12": {
        "page": 2,
        "x": 123,
        "y": 394,
        "w": 661,
        "h": 48
      },
      "f13": {
        "page": 2,
        "x": 122,
        "y": 429,
        "w": 661,
        "h": 48
      }
    }
  },
  "sainsburys": {
    "pages": [
      {
        "src": "/photo-samples/sainsburys-1.jpg",
        "width": 900,
        "height": 1200
      }
    ],
    "lines": {
      "r1": {
        "page": 1,
        "x": 273,
        "y": 292,
        "w": 349,
        "h": 40
      },
      "r2": {
        "page": 1,
        "x": 274,
        "y": 318,
        "w": 349,
        "h": 40
      },
      "r3": {
        "page": 1,
        "x": 276,
        "y": 345,
        "w": 349,
        "h": 40
      },
      "r4": {
        "page": 1,
        "x": 277,
        "y": 371,
        "w": 349,
        "h": 40
      }
    }
  },
  "menu": {
    "pages": [
      {
        "src": "/photo-samples/menu-1.jpg",
        "width": 900,
        "height": 1200
      }
    ],
    "lines": {
      "m1": {
        "page": 1,
        "x": 213,
        "y": 292,
        "w": 490,
        "h": 73
      },
      "m2": {
        "page": 1,
        "x": 211,
        "y": 350,
        "w": 490,
        "h": 73
      },
      "m3": {
        "page": 1,
        "x": 209,
        "y": 408,
        "w": 490,
        "h": 73
      },
      "m4": {
        "page": 1,
        "x": 207,
        "y": 466,
        "w": 490,
        "h": 73
      },
      "m5": {
        "page": 1,
        "x": 205,
        "y": 524,
        "w": 490,
        "h": 73
      }
    }
  },
  "blurry": {
    "pages": [
      {
        "src": "/photo-samples/blurry-1.jpg",
        "width": 900,
        "height": 1200
      }
    ],
    "lines": {}
  }
};
