import type { ChecklistTemplate, ChecklistInstance } from './types';

export const MOCK_SITES = ['Fitzroy Espresso', 'South Yarra', 'Richmond', 'Carlton'];

export const MOCK_USERS = [
  { id: 'u1', name: 'Ravi Mehta' },
  { id: 'u2', name: 'Cheryl Wong' },
  { id: 'u3', name: 'Jordan Beck' },
  { id: 'u4', name: 'Sam Torres' },
];

export const MOCK_TEMPLATES: ChecklistTemplate[] = [
  {
    id: 'tpl-1',
    name: 'Opening checks',
    sites: ['Fitzroy Espresso', 'South Yarra'],
    notifyUserIds: ['u2'],
    frequency: 'daily',
    timeOfDay: '07:00',
    assignedRoles: ['kitchen', 'manager'],
    active: true,
    questions: [
      {
        id: 'q1',
        name: 'Are all display fridges at correct temperature?',
        mandatory: true,
        allowPhoto: false,
        responseType: 'checkbox',
        followUpRules: [
          {
            id: 'fr1',
            condition: { type: 'unchecked' },
            followUpQuestionId: 'q1a',
          },
        ],
      },
      {
        id: 'q1a',
        name: 'Document the fridge issue and corrective action taken',
        mandatory: true,
        allowPhoto: true,
        responseType: 'text',
        followUpRules: [],
        parentQuestionId: 'q1',
      },
      {
        id: 'q2',
        name: 'Fridge 1 temperature (°C)',
        mandatory: true,
        allowPhoto: false,
        responseType: 'temperature',
        followUpRules: [
          {
            id: 'fr2',
            condition: { type: 'greater_than', value: 5 },
            followUpQuestionId: 'q2a',
          },
        ],
      },
      {
        id: 'q2a',
        name: 'Fridge is above safe temperature — describe corrective action',
        mandatory: true,
        allowPhoto: true,
        responseType: 'text',
        followUpRules: [],
        parentQuestionId: 'q2',
      },
      {
        id: 'q3',
        name: 'Are all cleaning checklists from close last night complete?',
        mandatory: true,
        allowPhoto: false,
        responseType: 'checkbox',
        followUpRules: [],
      },
      {
        id: 'q4',
        name: 'Is the coffee machine running correctly?',
        mandatory: true,
        allowPhoto: false,
        responseType: 'checkbox',
        followUpRules: [],
      },
      {
        id: 'q5',
        name: 'Any maintenance issues to log?',
        mandatory: false,
        allowPhoto: true,
        responseType: 'text',
        followUpRules: [],
      },
    ],
  },
  {
    id: 'tpl-2',
    name: 'Temperature log — cold chain',
    sites: ['Fitzroy Espresso', 'South Yarra', 'Richmond', 'Carlton'],
    notifyUserIds: ['u1', 'u2'],
    frequency: 'daily',
    timeOfDay: '09:00',
    assignedRoles: ['kitchen'],
    active: true,
    questions: [
      {
        id: 'qt1',
        name: 'Walk-in cool room temperature (°C)',
        mandatory: true,
        allowPhoto: false,
        responseType: 'temperature',
        followUpRules: [
          {
            id: 'fr3',
            condition: { type: 'greater_than', value: 4 },
            followUpQuestionId: 'qt1a',
          },
        ],
      },
      {
        id: 'qt1a',
        name: 'Cool room above 4°C — log corrective action and notify manager',
        mandatory: true,
        allowPhoto: true,
        responseType: 'text',
        followUpRules: [],
        parentQuestionId: 'qt1',
      },
      {
        id: 'qt2',
        name: 'Sandwich fridge temperature (°C)',
        mandatory: true,
        allowPhoto: false,
        responseType: 'temperature',
        followUpRules: [],
      },
      {
        id: 'qt3',
        name: 'Drinks fridge temperature (°C)',
        mandatory: true,
        allowPhoto: false,
        responseType: 'temperature',
        followUpRules: [],
      },
      {
        id: 'qt4',
        name: 'All labels checked for use-by dates?',
        mandatory: true,
        allowPhoto: false,
        responseType: 'checkbox',
        followUpRules: [
          {
            id: 'fr4',
            condition: { type: 'unchecked' },
            followUpQuestionId: 'qt4a',
          },
        ],
      },
      {
        id: 'qt4a',
        name: 'List items with expired or missing use-by dates',
        mandatory: true,
        allowPhoto: true,
        responseType: 'text',
        followUpRules: [],
        parentQuestionId: 'qt4',
      },
    ],
  },
  {
    id: 'tpl-3',
    name: 'Closing checks',
    sites: ['Fitzroy Espresso'],
    notifyUserIds: [],
    frequency: 'daily',
    timeOfDay: '17:00',
    assignedRoles: ['manager'],
    active: true,
    questions: [
      {
        id: 'qc1',
        name: 'All food stored correctly and labelled?',
        mandatory: true,
        allowPhoto: false,
        responseType: 'checkbox',
        followUpRules: [],
      },
      {
        id: 'qc2',
        name: 'Cash counted and reconciled?',
        mandatory: true,
        allowPhoto: false,
        responseType: 'checkbox',
        followUpRules: [],
      },
      {
        id: 'qc3',
        name: 'Total cash in drawer ($)',
        mandatory: true,
        allowPhoto: false,
        responseType: 'number',
        followUpRules: [],
      },
      {
        id: 'qc4',
        name: 'All cleaning tasks complete?',
        mandatory: true,
        allowPhoto: true,
        responseType: 'checkbox',
        followUpRules: [],
      },
      {
        id: 'qc5',
        name: 'Any incidents to report?',
        mandatory: false,
        allowPhoto: false,
        responseType: 'text',
        followUpRules: [],
      },
    ],
  },
  {
    id: 'tpl-4',
    name: 'Weekly equipment check',
    sites: ['Fitzroy Espresso', 'South Yarra', 'Richmond'],
    notifyUserIds: ['u3'],
    frequency: 'weekly',
    timeOfDay: '08:00',
    assignedRoles: ['manager'],
    active: false,
    questions: [
      {
        id: 'qe1',
        name: 'Coffee machine serviced this week?',
        mandatory: true,
        allowPhoto: false,
        responseType: 'checkbox',
        followUpRules: [],
      },
      {
        id: 'qe2',
        name: 'Grinder calibration checked?',
        mandatory: true,
        allowPhoto: false,
        responseType: 'checkbox',
        followUpRules: [],
      },
      {
        id: 'qe3',
        name: 'Any equipment faults to log?',
        mandatory: false,
        allowPhoto: true,
        responseType: 'text',
        followUpRules: [],
      },
    ],
  },
];

export const MOCK_INSTANCES: ChecklistInstance[] = [
  {
    id: 'inst-1',
    templateId: 'tpl-1',
    templateName: 'Opening checks',
    site: 'Fitzroy Espresso',
    status: 'pending',
    dueLabel: 'Due today · 7:00am',
    assignedRole: 'kitchen',
    questionCount: 5,
    answers: [],
  },
  {
    id: 'inst-2',
    templateId: 'tpl-2',
    templateName: 'Temperature log — cold chain',
    site: 'Fitzroy Espresso',
    status: 'in_progress',
    dueLabel: 'Due today · 9:00am',
    assignedRole: 'kitchen',
    questionCount: 4,
    answers: [
      { questionId: 'qt1', value: 3 },
    ],
  },
  {
    id: 'inst-3',
    templateId: 'tpl-3',
    templateName: 'Closing checks',
    site: 'Fitzroy Espresso',
    status: 'pending',
    dueLabel: 'Due today · 5:00pm',
    assignedRole: 'manager',
    questionCount: 5,
    answers: [],
  },
  {
    id: 'inst-4',
    templateId: 'tpl-1',
    templateName: 'Opening checks',
    site: 'South Yarra',
    status: 'complete',
    dueLabel: 'Completed today · 7:12am',
    assignedRole: 'kitchen',
    questionCount: 5,
    answers: [
      { questionId: 'q1', value: true },
      { questionId: 'q2', value: 3 },
      { questionId: 'q3', value: true },
      { questionId: 'q4', value: true },
      { questionId: 'q5', value: '' },
    ],
    completedAt: '7:12am',
    completedDate: '2026-04-04',
    completedBy: 'Ravi Mehta',
  },
];

export const MOCK_HISTORY: ChecklistInstance[] = [
  // Yesterday — 3 Apr
  {
    id: 'hist-1',
    templateId: 'tpl-1',
    templateName: 'Opening checks',
    site: 'Fitzroy Espresso',
    status: 'complete',
    dueLabel: 'Completed 3 Apr · 7:04am',
    assignedRole: 'kitchen',
    questionCount: 5,
    answers: [
      { questionId: 'q1', value: true },
      { questionId: 'q2', value: 4 },
      { questionId: 'q3', value: true },
      { questionId: 'q4', value: true },
      { questionId: 'q5', value: '' },
    ],
    completedAt: '7:04am',
    completedDate: '2026-04-03',
    completedBy: 'Ravi Mehta',
  },
  {
    id: 'hist-2',
    templateId: 'tpl-2',
    templateName: 'Temperature log — cold chain',
    site: 'Fitzroy Espresso',
    status: 'complete',
    dueLabel: 'Completed 3 Apr · 9:11am',
    assignedRole: 'kitchen',
    questionCount: 4,
    answers: [
      { questionId: 'qt1', value: 6 },
      { questionId: 'qt1a', value: 'Moved stock to backup fridge, called tech support. Fridge back to 3°C by 10am.' },
      { questionId: 'qt2', value: 4 },
      { questionId: 'qt3', value: 3 },
      { questionId: 'qt4', value: true },
    ],
    completedAt: '9:11am',
    completedDate: '2026-04-03',
    completedBy: 'Jordan Beck',
  },
  {
    id: 'hist-3',
    templateId: 'tpl-3',
    templateName: 'Closing checks',
    site: 'Fitzroy Espresso',
    status: 'complete',
    dueLabel: 'Completed 3 Apr · 5:22pm',
    assignedRole: 'manager',
    questionCount: 5,
    answers: [
      { questionId: 'qc1', value: true },
      { questionId: 'qc2', value: true },
      { questionId: 'qc3', value: 842 },
      { questionId: 'qc4', value: true },
      { questionId: 'qc5', value: '' },
    ],
    completedAt: '5:22pm',
    completedDate: '2026-04-03',
    completedBy: 'Cheryl Wong',
  },
  {
    id: 'hist-4',
    templateId: 'tpl-1',
    templateName: 'Opening checks',
    site: 'South Yarra',
    status: 'complete',
    dueLabel: 'Completed 3 Apr · 7:08am',
    assignedRole: 'kitchen',
    questionCount: 5,
    answers: [
      { questionId: 'q1', value: false },
      { questionId: 'q1a', value: 'Display fridge door seal broken. Placed a work order, moved cold items to backup unit.' },
      { questionId: 'q2', value: 7 },
      { questionId: 'q2a', value: 'Backup fridge used. Temp normal by 8am. Manager notified.' },
      { questionId: 'q3', value: true },
      { questionId: 'q4', value: true },
      { questionId: 'q5', value: '' },
    ],
    completedAt: '7:08am',
    completedDate: '2026-04-03',
    completedBy: 'Sam Torres',
  },
  // 2 Apr
  {
    id: 'hist-5',
    templateId: 'tpl-1',
    templateName: 'Opening checks',
    site: 'Fitzroy Espresso',
    status: 'complete',
    dueLabel: 'Completed 2 Apr · 6:58am',
    assignedRole: 'kitchen',
    questionCount: 5,
    answers: [
      { questionId: 'q1', value: true },
      { questionId: 'q2', value: 3 },
      { questionId: 'q3', value: true },
      { questionId: 'q4', value: true },
      { questionId: 'q5', value: '' },
    ],
    completedAt: '6:58am',
    completedDate: '2026-04-02',
    completedBy: 'Ravi Mehta',
  },
  {
    id: 'hist-6',
    templateId: 'tpl-2',
    templateName: 'Temperature log — cold chain',
    site: 'Fitzroy Espresso',
    status: 'complete',
    dueLabel: 'Completed 2 Apr · 9:03am',
    assignedRole: 'kitchen',
    questionCount: 4,
    answers: [
      { questionId: 'qt1', value: 3 },
      { questionId: 'qt2', value: 4 },
      { questionId: 'qt3', value: 3 },
      { questionId: 'qt4', value: true },
    ],
    completedAt: '9:03am',
    completedDate: '2026-04-02',
    completedBy: 'Jordan Beck',
  },
  {
    id: 'hist-7',
    templateId: 'tpl-3',
    templateName: 'Closing checks',
    site: 'Fitzroy Espresso',
    status: 'complete',
    dueLabel: 'Completed 2 Apr · 5:18pm',
    assignedRole: 'manager',
    questionCount: 5,
    answers: [
      { questionId: 'qc1', value: true },
      { questionId: 'qc2', value: true },
      { questionId: 'qc3', value: 910 },
      { questionId: 'qc4', value: true },
      { questionId: 'qc5', value: 'Customer left phone, returned same day.' },
    ],
    completedAt: '5:18pm',
    completedDate: '2026-04-02',
    completedBy: 'Cheryl Wong',
  },
  {
    id: 'hist-8',
    templateId: 'tpl-2',
    templateName: 'Temperature log — cold chain',
    site: 'Richmond',
    status: 'complete',
    dueLabel: 'Completed 2 Apr · 9:15am',
    assignedRole: 'kitchen',
    questionCount: 4,
    answers: [
      { questionId: 'qt1', value: 4 },
      { questionId: 'qt2', value: 3 },
      { questionId: 'qt3', value: 2 },
      { questionId: 'qt4', value: true },
    ],
    completedAt: '9:15am',
    completedDate: '2026-04-02',
    completedBy: 'Sam Torres',
  },
  // 1 Apr
  {
    id: 'hist-9',
    templateId: 'tpl-1',
    templateName: 'Opening checks',
    site: 'Fitzroy Espresso',
    status: 'complete',
    dueLabel: 'Completed 1 Apr · 7:01am',
    assignedRole: 'kitchen',
    questionCount: 5,
    answers: [
      { questionId: 'q1', value: true },
      { questionId: 'q2', value: 3 },
      { questionId: 'q3', value: true },
      { questionId: 'q4', value: true },
      { questionId: 'q5', value: '' },
    ],
    completedAt: '7:01am',
    completedDate: '2026-04-01',
    completedBy: 'Jordan Beck',
  },
  {
    id: 'hist-10',
    templateId: 'tpl-3',
    templateName: 'Closing checks',
    site: 'Fitzroy Espresso',
    status: 'complete',
    dueLabel: 'Completed 1 Apr · 5:30pm',
    assignedRole: 'manager',
    questionCount: 5,
    answers: [
      { questionId: 'qc1', value: true },
      { questionId: 'qc2', value: false },
      { questionId: 'qc3', value: 0 },
      { questionId: 'qc4', value: true },
      { questionId: 'qc5', value: 'POS system was down at end of day, cash reconciliation to be completed tomorrow morning.' },
    ],
    completedAt: '5:30pm',
    completedDate: '2026-04-01',
    completedBy: 'Cheryl Wong',
  },
];

export const ALL_COMPLETED_INSTANCES: ChecklistInstance[] = [
  ...MOCK_INSTANCES.filter((i) => i.status === 'complete'),
  ...MOCK_HISTORY,
];

export function getTemplateById(id: string): ChecklistTemplate | undefined {
  return MOCK_TEMPLATES.find((t) => t.id === id);
}

export function getInstanceById(id: string): ChecklistInstance | undefined {
  return [...MOCK_INSTANCES, ...MOCK_HISTORY].find((i) => i.id === id);
}

export function getTemplateForInstance(instance: ChecklistInstance): ChecklistTemplate | undefined {
  return MOCK_TEMPLATES.find((t) => t.id === instance.templateId);
}

export function getAllHistoryInstances(): ChecklistInstance[] {
  return ALL_COMPLETED_INSTANCES.sort((a, b) => {
    const dateA = a.completedDate ?? '0000-00-00';
    const dateB = b.completedDate ?? '0000-00-00';
    return dateB.localeCompare(dateA);
  });
}
