// Generates the sample "photos" for the photo delivery capture prototype:
// one JPEG per page in public/photo-samples, and the position of every line
// in components/Receiving/photo/samplePhotos.ts so the review screen can crop
// each line out of the real image. Needs `npm run dev` running.
// Uses the @playwright/test install in edify/web-v2. Run with
// PLAYWRIGHT_BROWSERS_PATH="$HOME/Library/Caches/ms-playwright" node scripts/photo-samples.mjs
import { createRequire } from 'node:module';
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(path.resolve(root, '../edify/web-v2/package.json'));
const { chromium } = require('@playwright/test');

const BASE = process.env.BASE_URL ?? 'http://127.0.0.1:3000';
const SAMPLES = [
  ['fd-note-clean', 1],
  ['fd-note', 2],
  ['fd-invoice', 2],
  ['sainsburys', 1],
  ['menu', 1],
  ['blurry', 1],
];

const outDir = path.join(root, 'public/photo-samples');
mkdirSync(outDir, { recursive: true });

const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1000, height: 1300 }, deviceScaleFactor: 1.5 });
const manifest = {};

for (const [sample, pages] of SAMPLES) {
  manifest[sample] = { pages: [], lines: {} };
  for (let p = 1; p <= pages; p++) {
    await page.goto(`${BASE}/dev/photo-samples?sample=${sample}&page=${p}`, { waitUntil: 'networkidle', timeout: 90000 });
    const frame = page.locator('[data-photo]');
    await frame.waitFor();
    const file = `${sample}-${p}.jpg`;
    await frame.screenshot({ path: path.join(outDir, file), type: 'jpeg', quality: 82 });
    const { width, height, lines } = await frame.evaluate((el) => {
      const f = el.getBoundingClientRect();
      const out = {};
      el.querySelectorAll('[data-line-id]').forEach((row) => {
        const r = row.getBoundingClientRect();
        out[row.getAttribute('data-line-id')] = {
          x: Math.round(r.left - f.left),
          y: Math.round(r.top - f.top),
          w: Math.round(r.width),
          h: Math.round(r.height),
        };
      });
      return { width: Math.round(f.width), height: Math.round(f.height), lines: out };
    });
    manifest[sample].pages.push({ src: `/photo-samples/${file}`, width, height });
    if (sample !== 'blurry') {
      for (const [id, box] of Object.entries(lines)) manifest[sample].lines[id] = { page: p, ...box };
    }
    console.log(`${file}: ${Object.keys(lines).length} lines`);
  }
}

await browser.close();

const ts = `// Generated by scripts/photo-samples.mjs. Do not edit by hand.
import type { SampleId } from './fixtures';

export interface PhotoBox {
  page: number;
  x: number;
  y: number;
  w: number;
  h: number;
}

export interface SamplePhoto {
  pages: { src: string; width: number; height: number }[];
  /** Where each document line sits on its page, in the page's own pixels. */
  lines: Record<string, PhotoBox>;
}

export const SAMPLE_PHOTOS: Record<SampleId, SamplePhoto> = ${JSON.stringify(manifest, null, 2)};
`;
writeFileSync(path.join(root, 'components/Receiving/photo/samplePhotos.ts'), ts);
console.log('Wrote samplePhotos.ts');
