/**
 * Farmer J Marylebone, Wednesday 16 April 2025. Real till export, one shop,
 * one trading day, aggregated from the row-level file Ed received
 * ("Sales Data.csv", 880 rows) by category, till code, channel and hour.
 *
 * What is in it: 2855 items, £6221.89 net, 10:00 to 14:59.
 * The export covers lunch only. There are no breakfast or evening rows,
 * so any breakfast or dinner figure elsewhere in the demo is modelled and
 * labelled as such.
 *
 * How to read it:
 *  - "Field Trays" rows are the protein tray sale (Amba Chicken Fieldtray
 *    Main, 144 on the day). Every tray also produces one "FT Grains" row
 *    (the base: Rice, Farmer's Grains, Sesame Cabbage, Spinach) and two
 *    "FT Sides" rows at £0. The base and side rows are what drive
 *    component demand for rice, grains and the sides.
 *  - "Fieldbowls" are the bowl format (smaller protein, base built in).
 *  - "Individual Portion" rows are extra mains and extra sides.
 *  - "FT Sauces" are the sauce choice; Green Tahini is the Green Shifka
 *    Tahini dressing, so it adds dressing demand.
 *  - Channel: instore and kiosk feed the main line; deliveroo and
 *    clickcollect feed the second make line.
 *
 * Generated file. Regenerate with the script in the handover if the
 * export changes; do not hand-edit.
 */

export type SalesChannel = 'instore' | 'kiosk' | 'deliveroo' | 'clickcollect';

export type SalesRow = {
  category: string;
  code: string;
  name: string;
  channel: SalesChannel;
  hour: number;
  items: number;
  net: number;
};

export const MARYLEBONE_SALES_DATE = '2025-04-16';
export const MARYLEBONE_SALES_TOTAL_ITEMS = 2855;
export const MARYLEBONE_SALES_TOTAL_NET = 6221.89;

export const MARYLEBONE_SALES_DAY: SalesRow[] = [
  { category: "FT Extras", code: "1000976", name: "Egg", channel: 'clickcollect', hour: 10, items: 1, net: 0.75 },
  { category: "FT Extras", code: "1003765", name: "Sesame Cucumber", channel: 'clickcollect', hour: 10, items: 1, net: 0.5 },
  { category: "FT Sauces", code: "102976", name: "Chimichurri", channel: 'clickcollect', hour: 10, items: 1, net: 0.5 },
  { category: "FT Sauces", code: "1001067", name: "No Sauce", channel: 'clickcollect', hour: 10, items: 1, net: 0 },
  { category: "FT Sauces", code: "102975", name: "Red Pepper", channel: 'clickcollect', hour: 10, items: 1, net: 0.5 },
  { category: "Set Fieldtrays", code: "1002194", name: "Butcher`s Cut", channel: 'clickcollect', hour: 10, items: 1, net: 10.63 },
  { category: "Set Fieldtrays", code: "1002193", name: "J`s Classic", channel: 'clickcollect', hour: 10, items: 2, net: 18.26 },
  { category: "Snacks/Impluse", code: "1000969", name: "Chocolate Chip Cookie", channel: 'clickcollect', hour: 10, items: 1, net: 1.95 },
  { category: "Coffee Milks", code: "103079", name: "ALMOND", channel: 'instore', hour: 11, items: 1, net: 0.42 },
  { category: "Coffee Milks", code: "103077", name: "FULL FAT", channel: 'instore', hour: 11, items: 2, net: 0 },
  { category: "Coffee Milks", code: "1000996", name: "FULL FAT", channel: 'instore', hour: 11, items: 2, net: 0 },
  { category: "Coffee Milks", code: "1000997", name: "OAT", channel: 'instore', hour: 11, items: 1, net: 0.42 },
  { category: "Coffee Milks", code: "103067", name: "SEMI SKIMMED", channel: 'instore', hour: 11, items: 2, net: 0 },
  { category: "Cold Drinks", code: "1003610", name: "Agua De Madre - Passion Fruit", channel: 'instore', hour: 11, items: 1, net: 3.13 },
  { category: "Cold Drinks", code: "1002531", name: "Apple Juice", channel: 'kiosk', hour: 11, items: 1, net: 2.71 },
  { category: "Cold Drinks", code: "103118", name: "Coke", channel: 'instore', hour: 11, items: 1, net: 1.25 },
  { category: "Cold Drinks", code: "1002627", name: "Dash Peach", channel: 'instore', hour: 11, items: 2, net: 3.26 },
  { category: "Cold Drinks", code: "103119", name: "Diet Coke", channel: 'deliveroo', hour: 11, items: 1, net: 1.5 },
  { category: "Cold Drinks", code: "103119", name: "Diet Coke", channel: 'instore', hour: 11, items: 1, net: 1.25 },
  { category: "Cold Drinks", code: "103119", name: "Diet Coke", channel: 'kiosk', hour: 11, items: 1, net: 1.25 },
  { category: "Cold Drinks", code: "1000977", name: "Farmers Lemonade", channel: 'instore', hour: 11, items: 2, net: 3.92 },
  { category: "Cold Drinks", code: "1000977", name: "Farmers Lemonade", channel: 'kiosk', hour: 11, items: 1, net: 1.96 },
  { category: "Cold Drinks", code: "1002085", name: "Orange Juice", channel: 'kiosk', hour: 11, items: 1, net: 2.71 },
  { category: "Cold Drinks", code: "103137", name: "Original - JARR", channel: 'deliveroo', hour: 11, items: 1, net: 3.96 },
  { category: "Cold Drinks", code: "103137", name: "Original - JARR", channel: 'instore', hour: 11, items: 1, net: 3.29 },
  { category: "Cold Drinks", code: "103123", name: "Sparkling Water", channel: 'instore', hour: 11, items: 1, net: 1.25 },
  { category: "Cold Drinks", code: "103122", name: "Still Water", channel: 'instore', hour: 11, items: 2, net: 2.5 },
  { category: "Cold Drinks", code: "1001982", name: "TRIP - Peach Ginger", channel: 'instore', hour: 11, items: 2, net: 5.42 },
  { category: "Field Trays", code: "1003748", name: "Amba Chicken Fieldtray Main", channel: 'deliveroo', hour: 11, items: 1, net: 11.63 },
  { category: "Field Trays", code: "1003748", name: "Amba Chicken Fieldtray Main", channel: 'instore', hour: 11, items: 12, net: 105.9 },
  { category: "Field Trays", code: "1001747", name: "Harissa Chicken Fieldtray Main", channel: 'clickcollect', hour: 11, items: 1, net: 9.13 },
  { category: "Field Trays", code: "1001747", name: "Harissa Chicken Fieldtray Main", channel: 'deliveroo', hour: 11, items: 2, net: 23.26 },
  { category: "Field Trays", code: "1001747", name: "Harissa Chicken Fieldtray Main", channel: 'instore', hour: 11, items: 6, net: 52.95 },
  { category: "Field Trays", code: "1001798", name: "Salmon Fieldtray Main", channel: 'deliveroo', hour: 11, items: 4, net: 55.84 },
  { category: "Field Trays", code: "1001798", name: "Salmon Fieldtray Main", channel: 'instore', hour: 11, items: 4, net: 41 },
  { category: "Field Trays", code: "1001798", name: "Salmon Fieldtray Main", channel: 'kiosk', hour: 11, items: 1, net: 10.79 },
  { category: "Field Trays", code: "1001750", name: "Steak Fieldtray Main", channel: 'deliveroo', hour: 11, items: 3, net: 39.87 },
  { category: "Field Trays", code: "1001750", name: "Steak Fieldtray Main", channel: 'instore', hour: 11, items: 4, net: 38.26 },
  { category: "Field Trays", code: "1001750", name: "Steak Fieldtray Main", channel: 'kiosk', hour: 11, items: 2, net: 21.26 },
  { category: "Field Trays", code: "1002885", name: "Tofu Fieldtray Main", channel: 'instore', hour: 11, items: 2, net: 16.43 },
  { category: "Fieldbowls", code: "1003760", name: "The Amba Bowl", channel: 'instore', hour: 11, items: 2, net: 14.92 },
  { category: "Fieldbowls", code: "1003761", name: "The Harissa Bowl", channel: 'kiosk', hour: 11, items: 1, net: 7.46 },
  { category: "Fieldbowls", code: "1003762", name: "The Salmon Bowl", channel: 'deliveroo', hour: 11, items: 1, net: 13.96 },
  { category: "Fieldbowls", code: "1003762", name: "The Salmon Bowl", channel: 'instore', hour: 11, items: 3, net: 32.37 },
  { category: "Fieldbowls", code: "1003763", name: "The Tofu Bowl", channel: 'instore', hour: 11, items: 1, net: 7.46 },
  { category: "FT Extras", code: "1000974", name: "Avocado", channel: 'instore', hour: 11, items: 1, net: 2 },
  { category: "FT Extras", code: "1000976", name: "Egg", channel: 'deliveroo', hour: 11, items: 3, net: 3 },
  { category: "FT Extras", code: "1000976", name: "Egg", channel: 'instore', hour: 11, items: 1, net: 0.75 },
  { category: "FT Extras", code: "1003766", name: "Pickled Cucumber", channel: 'instore', hour: 11, items: 1, net: 0.42 },
  { category: "FT Extras", code: "1003767", name: "Pickled Onion", channel: 'instore', hour: 11, items: 1, net: 0.33 },
  { category: "FT Grains", code: "98680", name: "Farmer's Grains", channel: 'deliveroo', hour: 11, items: 3, net: 0 },
  { category: "FT Grains", code: "98680", name: "Farmer's Grains", channel: 'instore', hour: 11, items: 17, net: 0 },
  { category: "FT Grains", code: "98679", name: "Rice", channel: 'clickcollect', hour: 11, items: 1, net: 0 },
  { category: "FT Grains", code: "98679", name: "Rice", channel: 'deliveroo', hour: 11, items: 6, net: 0 },
  { category: "FT Grains", code: "98679", name: "Rice", channel: 'instore', hour: 11, items: 9, net: 0 },
  { category: "FT Grains", code: "98679", name: "Rice", channel: 'kiosk', hour: 11, items: 3, net: 0 },
  { category: "FT Grains", code: "1003740", name: "Sesame Cabbage", channel: 'instore', hour: 11, items: 1, net: 0 },
  { category: "FT Grains", code: "98681", name: "Spinach", channel: 'deliveroo', hour: 11, items: 1, net: 0 },
  { category: "FT Grains", code: "98681", name: "Spinach", channel: 'instore', hour: 11, items: 1, net: 0 },
  { category: "FT Sauces", code: "102976", name: "Chimichurri", channel: 'deliveroo', hour: 11, items: 6, net: 4.5 },
  { category: "FT Sauces", code: "102976", name: "Chimichurri", channel: 'instore', hour: 11, items: 2, net: 0.75 },
  { category: "FT Sauces", code: "102976", name: "Chimichurri", channel: 'kiosk', hour: 11, items: 1, net: 0.5 },
  { category: "FT Sauces", code: "102977", name: "Green Tahini", channel: 'deliveroo', hour: 11, items: 1, net: 0.75 },
  { category: "FT Sauces", code: "102977", name: "Green Tahini", channel: 'instore', hour: 11, items: 2, net: 0.84 },
  { category: "FT Sauces", code: "1001981", name: "J’s Aioli", channel: 'clickcollect', hour: 11, items: 1, net: 0.5 },
  { category: "FT Sauces", code: "1001981", name: "J’s Aioli", channel: 'deliveroo', hour: 11, items: 1, net: 0.75 },
  { category: "FT Sauces", code: "1001981", name: "J’s Aioli", channel: 'kiosk', hour: 11, items: 1, net: 0.5 },
  { category: "FT Sauces", code: "1001067", name: "No Sauce", channel: 'deliveroo', hour: 11, items: 6, net: 0 },
  { category: "FT Sauces", code: "1001067", name: "No Sauce", channel: 'instore', hour: 11, items: 28, net: 0 },
  { category: "FT Sauces", code: "1001067", name: "No Sauce", channel: 'kiosk', hour: 11, items: 1, net: 0 },
  { category: "FT Sauces", code: "102975", name: "Red Pepper", channel: 'deliveroo', hour: 11, items: 1, net: 0.75 },
  { category: "FT Sauces", code: "102975", name: "Red Pepper", channel: 'kiosk', hour: 11, items: 1, net: 0.5 },
  { category: "FT Sides", code: "98670", name: "Broccoli", channel: 'clickcollect', hour: 11, items: 1, net: 0 },
  { category: "FT Sides", code: "98670", name: "Broccoli", channel: 'deliveroo', hour: 11, items: 3, net: 0 },
  { category: "FT Sides", code: "98670", name: "Broccoli", channel: 'instore', hour: 11, items: 8, net: 0 },
  { category: "FT Sides", code: "98670", name: "Broccoli", channel: 'kiosk', hour: 11, items: 2, net: 0 },
  { category: "FT Sides", code: "98668", name: "Cashew Kale Miso Slaw", channel: 'clickcollect', hour: 11, items: 1, net: 0 },
  { category: "FT Sides", code: "98668", name: "Cashew Kale Miso Slaw", channel: 'deliveroo', hour: 11, items: 3, net: 0 },
  { category: "FT Sides", code: "98668", name: "Cashew Kale Miso Slaw", channel: 'instore', hour: 11, items: 10, net: 0 },
  { category: "FT Sides", code: "98690", name: "Cauliflower", channel: 'deliveroo', hour: 11, items: 3, net: 0 },
  { category: "FT Sides", code: "98690", name: "Cauliflower", channel: 'instore', hour: 11, items: 13, net: 0 },
  { category: "FT Sides", code: "1003583", name: "Chickpea + Pickles", channel: 'deliveroo', hour: 11, items: 1, net: 0 },
  { category: "FT Sides", code: "1003583", name: "Chickpea + Pickles", channel: 'instore', hour: 11, items: 1, net: 0 },
  { category: "FT Sides", code: "1003742", name: "IOW Tomato", channel: 'deliveroo', hour: 11, items: 1, net: 0 },
  { category: "FT Sides", code: "1003742", name: "IOW Tomato", channel: 'instore', hour: 11, items: 3, net: 0 },
  { category: "FT Sides", code: "1001060", name: "Mac & Cheese", channel: 'deliveroo', hour: 11, items: 1, net: 0 },
  { category: "FT Sides", code: "1001060", name: "Mac & Cheese", channel: 'instore', hour: 11, items: 5, net: 0 },
  { category: "FT Sides", code: "1001060", name: "Mac & Cheese", channel: 'kiosk', hour: 11, items: 2, net: 0 },
  { category: "FT Sides", code: "1003743", name: "Parmesan Potatoes", channel: 'deliveroo', hour: 11, items: 1, net: 0 },
  { category: "FT Sides", code: "1003743", name: "Parmesan Potatoes", channel: 'instore', hour: 11, items: 7, net: 0 },
  { category: "FT Sides", code: "1003743", name: "Parmesan Potatoes", channel: 'kiosk', hour: 11, items: 2, net: 0 },
  { category: "FT Sides", code: "1003741", name: "Spring Feta Caesar", channel: 'deliveroo', hour: 11, items: 3, net: 0 },
  { category: "FT Sides", code: "1003741", name: "Spring Feta Caesar", channel: 'instore', hour: 11, items: 1, net: 0 },
  { category: "FT Sides", code: "98692", name: "Sweet Potato", channel: 'deliveroo', hour: 11, items: 3, net: 0 },
  { category: "FT Sides", code: "98692", name: "Sweet Potato", channel: 'instore', hour: 11, items: 7, net: 0 },
  { category: "Hot Drinks", code: "103054", name: "Americano", channel: 'instore', hour: 11, items: 2, net: 5 },
  { category: "Hot Drinks", code: "103055", name: "Cappuccino", channel: 'instore', hour: 11, items: 1, net: 2.92 },
  { category: "Hot Drinks", code: "103065", name: "Chai Latte", channel: 'instore', hour: 11, items: 1, net: 3.29 },
  { category: "Hot Drinks", code: "1000966", name: "Decaff option", channel: 'instore', hour: 11, items: 1, net: 0.83 },
  { category: "Hot Drinks", code: "103081", name: "Espresso", channel: 'instore', hour: 11, items: 1, net: 2.08 },
  { category: "Hot Drinks", code: "103053", name: "Flat White", channel: 'instore', hour: 11, items: 3, net: 8.49 },
  { category: "Hot Drinks", code: "103056", name: "Latte", channel: 'instore', hour: 11, items: 1, net: 2.92 },
  { category: "Hot Drinks", code: "103063", name: "Teas", channel: 'instore', hour: 11, items: 1, net: 1.67 },
  { category: "Individual Portion", code: "98655", name: "Broccoli Extra Side", channel: 'deliveroo', hour: 11, items: 1, net: 7.5 },
  { category: "Individual Portion", code: "98663", name: "Cashew Kale Miso Slaw Extra Side", channel: 'deliveroo', hour: 11, items: 1, net: 4.5 },
  { category: "Individual Portion", code: "98663", name: "Cashew Kale Miso Slaw Extra Side", channel: 'instore', hour: 11, items: 1, net: 3.5 },
  { category: "Individual Portion", code: "98656", name: "Cauliflower Extra Side", channel: 'deliveroo', hour: 11, items: 1, net: 3.75 },
  { category: "Individual Portion", code: "1003587", name: "Chickpea + Pickles Extra Side", channel: 'deliveroo', hour: 11, items: 1, net: 4.5 },
  { category: "Individual Portion", code: "1001785", name: "Gotcha Salmon Extra Main", channel: 'instore', hour: 11, items: 1, net: 6.25 },
  { category: "Individual Portion", code: "1001518", name: "Harissa Chicken Extra Main", channel: 'deliveroo', hour: 11, items: 1, net: 6.67 },
  { category: "Individual Portion", code: "98650", name: "Steak Extra Main", channel: 'instore', hour: 11, items: 2, net: 11.66 },
  { category: "Individual Portion", code: "98658", name: "Sweet Potato Extra Side", channel: 'deliveroo', hour: 11, items: 1, net: 7.5 },
  { category: "Individual Portion", code: "98658", name: "Sweet Potato Extra Side", channel: 'instore', hour: 11, items: 1, net: 2.92 },
  { category: "Set Fieldtrays", code: "1002194", name: "Butcher`s Cut", channel: 'deliveroo', hour: 11, items: 1, net: 13.29 },
  { category: "Set Fieldtrays", code: "1002194", name: "Butcher`s Cut", channel: 'kiosk', hour: 11, items: 1, net: 10.63 },
  { category: "Set Fieldtrays", code: "1002193", name: "J`s Classic", channel: 'deliveroo', hour: 11, items: 3, net: 46.51 },
  { category: "Snacks/Impluse", code: "1001445", name: "Banana Bread", channel: 'deliveroo', hour: 11, items: 1, net: 7 },
  { category: "Snacks/Impluse", code: "1001445", name: "Banana Bread", channel: 'instore', hour: 11, items: 1, net: 3 },
  { category: "Snacks/Impluse", code: "1000969", name: "Chocolate Chip Cookie", channel: 'deliveroo', hour: 11, items: 3, net: 14.75 },
  { category: "Snacks/Impluse", code: "1000969", name: "Chocolate Chip Cookie", channel: 'instore', hour: 11, items: 4, net: 7.16 },
  { category: "Snacks/Impluse", code: "1002665", name: "Chocolate Maple Banana Cupcake", channel: 'instore', hour: 11, items: 1, net: 3.33 },
  { category: "Snacks/Impluse", code: "1003611", name: "Oat Cranberry Cookie", channel: 'instore', hour: 11, items: 3, net: 5.53 },
  { category: "Snacks/Impluse", code: "1002447", name: "Pitta Chips Rosemary", channel: 'instore', hour: 11, items: 1, net: 1.46 },
  { category: "Tea Options", code: "1001404", name: "Peppermint tea", channel: 'instore', hour: 11, items: 1, net: 0 },
  { category: "Coffee Milks", code: "103072", name: "BLACK", channel: 'instore', hour: 12, items: 2, net: 0 },
  { category: "Coffee Milks", code: "103078", name: "OAT", channel: 'instore', hour: 12, items: 1, net: 0.42 },
  { category: "Coffee Milks", code: "103069", name: "OAT", channel: 'instore', hour: 12, items: 1, net: 0 },
  { category: "Coffee Milks", code: "1000997", name: "OAT", channel: 'instore', hour: 12, items: 1, net: 0.42 },
  { category: "Coffee Milks", code: "1000998", name: "SEMI SKIMMED", channel: 'instore', hour: 12, items: 1, net: 0 },
  { category: "Cold Drinks", code: "1003610", name: "Agua De Madre - Passion Fruit", channel: 'deliveroo', hour: 12, items: 1, net: 3.96 },
  { category: "Cold Drinks", code: "1003610", name: "Agua De Madre - Passion Fruit", channel: 'instore', hour: 12, items: 1, net: 3.13 },
  { category: "Cold Drinks", code: "1003118", name: "Agua De Madre - Pink Grapefruit", channel: 'instore', hour: 12, items: 3, net: 9.39 },
  { category: "Cold Drinks", code: "103118", name: "Coke", channel: 'instore', hour: 12, items: 1, net: 1.25 },
  { category: "Cold Drinks", code: "103118", name: "Coke", channel: 'kiosk', hour: 12, items: 1, net: 1.25 },
  { category: "Cold Drinks", code: "1002627", name: "Dash Peach", channel: 'deliveroo', hour: 12, items: 1, net: 2.08 },
  { category: "Cold Drinks", code: "1002627", name: "Dash Peach", channel: 'instore', hour: 12, items: 2, net: 3.26 },
  { category: "Cold Drinks", code: "103119", name: "Diet Coke", channel: 'instore', hour: 12, items: 15, net: 18.25 },
  { category: "Cold Drinks", code: "103119", name: "Diet Coke", channel: 'kiosk', hour: 12, items: 1, net: 1.25 },
  { category: "Cold Drinks", code: "1000977", name: "Farmers Lemonade", channel: 'deliveroo', hour: 12, items: 1, net: 2.46 },
  { category: "Cold Drinks", code: "1000977", name: "Farmers Lemonade", channel: 'instore', hour: 12, items: 3, net: 5.49 },
  { category: "Cold Drinks", code: "1000977", name: "Farmers Lemonade", channel: 'kiosk', hour: 12, items: 1, net: 1.96 },
  { category: "Cold Drinks", code: "1002085", name: "Orange Juice", channel: 'deliveroo', hour: 12, items: 1, net: 3.46 },
  { category: "Cold Drinks", code: "103137", name: "Original - JARR", channel: 'deliveroo', hour: 12, items: 1, net: 3.96 },
  { category: "Cold Drinks", code: "103137", name: "Original - JARR", channel: 'instore', hour: 12, items: 1, net: 3.29 },
  { category: "Cold Drinks", code: "103136", name: "Passion Fruit- JARR", channel: 'clickcollect', hour: 12, items: 1, net: 2.63 },
  { category: "Cold Drinks", code: "103136", name: "Passion Fruit- JARR", channel: 'instore', hour: 12, items: 4, net: 16.45 },
  { category: "Cold Drinks", code: "103123", name: "Sparkling Water", channel: 'instore', hour: 12, items: 2, net: 2.5 },
  { category: "Cold Drinks", code: "103122", name: "Still Water", channel: 'instore', hour: 12, items: 3, net: 3.75 },
  { category: "Cold Drinks", code: "1001983", name: "TRIP- Elderflower Mint", channel: 'instore', hour: 12, items: 1, net: 2.71 },
  { category: "Fam Of 4", code: "1001604", name: "Brown Rice X4", channel: 'deliveroo', hour: 12, items: 1, net: 5.83 },
  { category: "Fam Of 4", code: "1001615", name: "Cauliflower X4", channel: 'deliveroo', hour: 12, items: 1, net: 12.5 },
  { category: "Field Trays", code: "1003748", name: "Amba Chicken Fieldtray Main", channel: 'deliveroo', hour: 12, items: 1, net: 11.63 },
  { category: "Field Trays", code: "1003748", name: "Amba Chicken Fieldtray Main", channel: 'instore', hour: 12, items: 57, net: 515.83 },
  { category: "Field Trays", code: "1003748", name: "Amba Chicken Fieldtray Main", channel: 'kiosk', hour: 12, items: 3, net: 23.73 },
  { category: "Field Trays", code: "1001583", name: "Broccoli Fieldtray Main", channel: 'deliveroo', hour: 12, items: 1, net: 9.96 },
  { category: "Field Trays", code: "1001584", name: "Cauliflower Fieldtray Main", channel: 'instore', hour: 12, items: 2, net: 15.42 },
  { category: "Field Trays", code: "1003591", name: "Chickpea + Pickles Fieldtray Main", channel: 'instore', hour: 12, items: 1, net: 7.71 },
  { category: "Field Trays", code: "1001747", name: "Harissa Chicken Fieldtray Main", channel: 'clickcollect', hour: 12, items: 5, net: 38.33 },
  { category: "Field Trays", code: "1001747", name: "Harissa Chicken Fieldtray Main", channel: 'deliveroo', hour: 12, items: 7, net: 81.41 },
  { category: "Field Trays", code: "1001747", name: "Harissa Chicken Fieldtray Main", channel: 'instore', hour: 12, items: 45, net: 388.89 },
  { category: "Field Trays", code: "1001747", name: "Harissa Chicken Fieldtray Main", channel: 'kiosk', hour: 12, items: 5, net: 45.65 },
  { category: "Field Trays", code: "1001748", name: "Mac & Cheese Fieldtray Main", channel: 'deliveroo', hour: 12, items: 1, net: 9.96 },
  { category: "Field Trays", code: "1001748", name: "Mac & Cheese Fieldtray Main", channel: 'instore', hour: 12, items: 4, net: 30.84 },
  { category: "Field Trays", code: "1001748", name: "Mac & Cheese Fieldtray Main", channel: 'kiosk', hour: 12, items: 1, net: 7.71 },
  { category: "Field Trays", code: "1003751", name: "Parmesan Potatoes Fieldtray Main", channel: 'kiosk', hour: 12, items: 1, net: 7.71 },
  { category: "Field Trays", code: "1001798", name: "Salmon Fieldtray Main", channel: 'clickcollect', hour: 12, items: 1, net: 10.79 },
  { category: "Field Trays", code: "1001798", name: "Salmon Fieldtray Main", channel: 'deliveroo', hour: 12, items: 1, net: 13.96 },
  { category: "Field Trays", code: "1001798", name: "Salmon Fieldtray Main", channel: 'instore', hour: 12, items: 31, net: 326.93 },
  { category: "Field Trays", code: "1001798", name: "Salmon Fieldtray Main", channel: 'kiosk', hour: 12, items: 1, net: 10.79 },
  { category: "Field Trays", code: "1001750", name: "Steak Fieldtray Main", channel: 'deliveroo', hour: 12, items: 5, net: 66.45 },
  { category: "Field Trays", code: "1001750", name: "Steak Fieldtray Main", channel: 'instore', hour: 12, items: 12, net: 127.56 },
  { category: "Field Trays", code: "1001750", name: "Steak Fieldtray Main", channel: 'kiosk', hour: 12, items: 4, net: 36.13 },
  { category: "Field Trays", code: "1001587", name: "Sweet Potato Fieldtray Main", channel: 'kiosk', hour: 12, items: 2, net: 13.88 },
  { category: "Field Trays", code: "1002885", name: "Tofu Fieldtray Main", channel: 'deliveroo', hour: 12, items: 1, net: 11.63 },
  { category: "Field Trays", code: "1002885", name: "Tofu Fieldtray Main", channel: 'instore', hour: 12, items: 7, net: 62.08 },
  { category: "Field Trays", code: "1002885", name: "Tofu Fieldtray Main", channel: 'kiosk', hour: 12, items: 1, net: 7.3 },
  { category: "Fieldbowls", code: "1003760", name: "The Amba Bowl", channel: 'instore', hour: 12, items: 8, net: 67.14 },
  { category: "Fieldbowls", code: "1003761", name: "The Harissa Bowl", channel: 'deliveroo', hour: 12, items: 3, net: 27.39 },
  { category: "Fieldbowls", code: "1003761", name: "The Harissa Bowl", channel: 'instore', hour: 12, items: 2, net: 14.92 },
  { category: "Fieldbowls", code: "1003761", name: "The Harissa Bowl", channel: 'kiosk', hour: 12, items: 1, net: 7.46 },
  { category: "Fieldbowls", code: "1003762", name: "The Salmon Bowl", channel: 'deliveroo', hour: 12, items: 1, net: 13.96 },
  { category: "Fieldbowls", code: "1003762", name: "The Salmon Bowl", channel: 'instore', hour: 12, items: 2, net: 32.37 },
  { category: "Fieldbowls", code: "1003763", name: "The Tofu Bowl", channel: 'deliveroo', hour: 12, items: 1, net: 9.13 },
  { category: "Fieldbowls", code: "1003763", name: "The Tofu Bowl", channel: 'instore', hour: 12, items: 6, net: 44.76 },
  { category: "Fieldbowls", code: "1003763", name: "The Tofu Bowl", channel: 'kiosk', hour: 12, items: 3, net: 20.89 },
  { category: "FT Extras", code: "1000974", name: "Avocado", channel: 'deliveroo', hour: 12, items: 3, net: 8.25 },
  { category: "FT Extras", code: "1000974", name: "Avocado", channel: 'instore', hour: 12, items: 4, net: 7.67 },
  { category: "FT Extras", code: "1000976", name: "Egg", channel: 'deliveroo', hour: 12, items: 3, net: 3 },
  { category: "FT Extras", code: "1000976", name: "Egg", channel: 'instore', hour: 12, items: 3, net: 2.75 },
  { category: "FT Extras", code: "1000976", name: "Egg", channel: 'kiosk', hour: 12, items: 1, net: 0.75 },
  { category: "FT Extras", code: "1003766", name: "Pickled Cucumber", channel: 'instore', hour: 12, items: 2, net: 1 },
  { category: "FT Extras", code: "1003766", name: "Pickled Cucumber", channel: 'kiosk', hour: 12, items: 1, net: 0.5 },
  { category: "FT Extras", code: "1003767", name: "Pickled Onion", channel: 'instore', hour: 12, items: 3, net: 1.42 },
  { category: "FT Extras", code: "1003810", name: "Pickled Onion", channel: 'instore', hour: 12, items: 1, net: 0.5 },
  { category: "FT Extras", code: "1003767", name: "Pickled Onion", channel: 'kiosk', hour: 12, items: 4, net: 2 },
  { category: "FT Extras", code: "1003765", name: "Sesame Cucumber", channel: 'clickcollect', hour: 12, items: 1, net: 0.5 },
  { category: "FT Extras", code: "1003765", name: "Sesame Cucumber", channel: 'deliveroo', hour: 12, items: 2, net: 1.5 },
  { category: "FT Extras", code: "1003765", name: "Sesame Cucumber", channel: 'instore', hour: 12, items: 2, net: 0.82 },
  { category: "FT Grains", code: "98680", name: "Farmer's Grains", channel: 'deliveroo', hour: 12, items: 5, net: 0 },
  { category: "FT Grains", code: "98680", name: "Farmer's Grains", channel: 'instore', hour: 12, items: 46, net: 0 },
  { category: "FT Grains", code: "98679", name: "Rice", channel: 'clickcollect', hour: 12, items: 4, net: 0 },
  { category: "FT Grains", code: "98679", name: "Rice", channel: 'deliveroo', hour: 12, items: 7, net: 0 },
  { category: "FT Grains", code: "98679", name: "Rice", channel: 'instore', hour: 12, items: 88, net: 0 },
  { category: "FT Grains", code: "98679", name: "Rice", channel: 'kiosk', hour: 12, items: 9, net: 0 },
  { category: "FT Grains", code: "1003740", name: "Sesame Cabbage", channel: 'deliveroo', hour: 12, items: 2, net: 0 },
  { category: "FT Grains", code: "1003740", name: "Sesame Cabbage", channel: 'instore', hour: 12, items: 17, net: 0 },
  { category: "FT Grains", code: "1003740", name: "Sesame Cabbage", channel: 'kiosk', hour: 12, items: 6, net: 0 },
  { category: "FT Grains", code: "98681", name: "Spinach", channel: 'clickcollect', hour: 12, items: 2, net: 0 },
  { category: "FT Grains", code: "98681", name: "Spinach", channel: 'deliveroo', hour: 12, items: 3, net: 0 },
  { category: "FT Grains", code: "98681", name: "Spinach", channel: 'instore', hour: 12, items: 8, net: 0 },
  { category: "FT Grains", code: "98681", name: "Spinach", channel: 'kiosk', hour: 12, items: 3, net: 0 },
  { category: "FT Sauces", code: "102976", name: "Chimichurri", channel: 'deliveroo', hour: 12, items: 6, net: 4.5 },
  { category: "FT Sauces", code: "102976", name: "Chimichurri", channel: 'instore', hour: 12, items: 3, net: 1.5 },
  { category: "FT Sauces", code: "1000961", name: "Chimichurri", channel: 'instore', hour: 12, items: 1, net: 1 },
  { category: "FT Sauces", code: "102976", name: "Chimichurri", channel: 'kiosk', hour: 12, items: 2, net: 1 },
  { category: "FT Sauces", code: "102977", name: "Green Tahini", channel: 'deliveroo', hour: 12, items: 1, net: 0.75 },
  { category: "FT Sauces", code: "102977", name: "Green Tahini", channel: 'instore', hour: 12, items: 6, net: 2.66 },
  { category: "FT Sauces", code: "1000964", name: "Green Tahini", channel: 'instore', hour: 12, items: 4, net: 1.84 },
  { category: "FT Sauces", code: "1001981", name: "J’s Aioli", channel: 'deliveroo', hour: 12, items: 6, net: 4.5 },
  { category: "FT Sauces", code: "1001974", name: "J’s Aioli", channel: 'instore', hour: 12, items: 1, net: 0.5 },
  { category: "FT Sauces", code: "1001981", name: "J’s Aioli", channel: 'instore', hour: 12, items: 3, net: 1.5 },
  { category: "FT Sauces", code: "1001981", name: "J’s Aioli", channel: 'kiosk', hour: 12, items: 2, net: 0.9 },
  { category: "FT Sauces", code: "1001067", name: "No Sauce", channel: 'clickcollect', hour: 12, items: 6, net: 0 },
  { category: "FT Sauces", code: "1001067", name: "No Sauce", channel: 'deliveroo', hour: 12, items: 9, net: 0 },
  { category: "FT Sauces", code: "1001067", name: "No Sauce", channel: 'instore', hour: 12, items: 159, net: 0 },
  { category: "FT Sauces", code: "1001067", name: "No Sauce", channel: 'kiosk', hour: 12, items: 17, net: 0 },
  { category: "FT Sauces", code: "102975", name: "Red Pepper", channel: 'deliveroo', hour: 12, items: 1, net: 0.75 },
  { category: "FT Sauces", code: "102975", name: "Red Pepper", channel: 'instore', hour: 12, items: 6, net: 3 },
  { category: "FT Sauces", code: "1000963", name: "Red Pepper", channel: 'instore', hour: 12, items: 1, net: 0.42 },
  { category: "FT Sauces", code: "102975", name: "Red Pepper", channel: 'kiosk', hour: 12, items: 2, net: 1 },
  { category: "FT Sides", code: "98670", name: "Broccoli", channel: 'clickcollect', hour: 12, items: 2, net: 0 },
  { category: "FT Sides", code: "98670", name: "Broccoli", channel: 'deliveroo', hour: 12, items: 5, net: 0 },
  { category: "FT Sides", code: "98670", name: "Broccoli", channel: 'instore', hour: 12, items: 39, net: 0 },
  { category: "FT Sides", code: "98670", name: "Broccoli", channel: 'kiosk', hour: 12, items: 4, net: 0 },
  { category: "FT Sides", code: "98668", name: "Cashew Kale Miso Slaw", channel: 'clickcollect', hour: 12, items: 4, net: 0 },
  { category: "FT Sides", code: "98668", name: "Cashew Kale Miso Slaw", channel: 'deliveroo', hour: 12, items: 1, net: 0 },
  { category: "FT Sides", code: "98668", name: "Cashew Kale Miso Slaw", channel: 'instore', hour: 12, items: 42, net: 0 },
  { category: "FT Sides", code: "98668", name: "Cashew Kale Miso Slaw", channel: 'kiosk', hour: 12, items: 4, net: 0 },
  { category: "FT Sides", code: "98690", name: "Cauliflower", channel: 'deliveroo', hour: 12, items: 3, net: 0 },
  { category: "FT Sides", code: "98690", name: "Cauliflower", channel: 'instore', hour: 12, items: 50, net: 0 },
  { category: "FT Sides", code: "1003583", name: "Chickpea + Pickles", channel: 'clickcollect', hour: 12, items: 2, net: 0 },
  { category: "FT Sides", code: "1003583", name: "Chickpea + Pickles", channel: 'deliveroo', hour: 12, items: 2, net: 0 },
  { category: "FT Sides", code: "1003583", name: "Chickpea + Pickles", channel: 'instore', hour: 12, items: 23, net: 0 },
  { category: "FT Sides", code: "1003583", name: "Chickpea + Pickles", channel: 'kiosk', hour: 12, items: 1, net: 0 },
  { category: "FT Sides", code: "1003742", name: "IOW Tomato", channel: 'clickcollect', hour: 12, items: 1, net: 0 },
  { category: "FT Sides", code: "1003742", name: "IOW Tomato", channel: 'deliveroo', hour: 12, items: 3, net: 0 },
  { category: "FT Sides", code: "1003742", name: "IOW Tomato", channel: 'instore', hour: 12, items: 30, net: 0 },
  { category: "FT Sides", code: "1003742", name: "IOW Tomato", channel: 'kiosk', hour: 12, items: 2, net: 0 },
  { category: "FT Sides", code: "1001060", name: "Mac & Cheese", channel: 'deliveroo', hour: 12, items: 6, net: 0 },
  { category: "FT Sides", code: "1001060", name: "Mac & Cheese", channel: 'instore', hour: 12, items: 46, net: 0 },
  { category: "FT Sides", code: "1001060", name: "Mac & Cheese", channel: 'kiosk', hour: 12, items: 9, net: 0 },
  { category: "FT Sides", code: "1003743", name: "Parmesan Potatoes", channel: 'deliveroo', hour: 12, items: 4, net: 0 },
  { category: "FT Sides", code: "1003743", name: "Parmesan Potatoes", channel: 'instore', hour: 12, items: 22, net: 0 },
  { category: "FT Sides", code: "1003743", name: "Parmesan Potatoes", channel: 'kiosk', hour: 12, items: 4, net: 0 },
  { category: "FT Sides", code: "1003741", name: "Spring Feta Caesar", channel: 'clickcollect', hour: 12, items: 1, net: 0 },
  { category: "FT Sides", code: "1003741", name: "Spring Feta Caesar", channel: 'deliveroo', hour: 12, items: 4, net: 0 },
  { category: "FT Sides", code: "1003741", name: "Spring Feta Caesar", channel: 'instore', hour: 12, items: 24, net: 0 },
  { category: "FT Sides", code: "1003741", name: "Spring Feta Caesar", channel: 'kiosk', hour: 12, items: 5, net: 0 },
  { category: "FT Sides", code: "98692", name: "Sweet Potato", channel: 'clickcollect', hour: 12, items: 2, net: 0 },
  { category: "FT Sides", code: "98692", name: "Sweet Potato", channel: 'deliveroo', hour: 12, items: 5, net: 0 },
  { category: "FT Sides", code: "98692", name: "Sweet Potato", channel: 'instore', hour: 12, items: 39, net: 0 },
  { category: "FT Sides", code: "98692", name: "Sweet Potato", channel: 'kiosk', hour: 12, items: 7, net: 0 },
  { category: "Hot Drinks", code: "103054", name: "Americano", channel: 'instore', hour: 12, items: 3, net: 7.5 },
  { category: "Hot Drinks", code: "103055", name: "Cappuccino", channel: 'instore', hour: 12, items: 1, net: 2.92 },
  { category: "Hot Drinks", code: "103053", name: "Flat White", channel: 'instore', hour: 12, items: 1, net: 2.83 },
  { category: "Hot Drinks", code: "103056", name: "Latte", channel: 'instore', hour: 12, items: 1, net: 2.92 },
  { category: "Hot Drinks", code: "103063", name: "Teas", channel: 'instore', hour: 12, items: 2, net: 3.34 },
  { category: "Individual Portion", code: "1003747", name: "Amba Chicken Extra Main", channel: 'deliveroo', hour: 12, items: 2, net: 13.34 },
  { category: "Individual Portion", code: "1003747", name: "Amba Chicken Extra Main", channel: 'instore', hour: 12, items: 2, net: 8.34 },
  { category: "Individual Portion", code: "98655", name: "Broccoli Extra Side", channel: 'deliveroo', hour: 12, items: 1, net: 3.75 },
  { category: "Individual Portion", code: "98655", name: "Broccoli Extra Side", channel: 'instore', hour: 12, items: 2, net: 8.75 },
  { category: "Individual Portion", code: "98663", name: "Cashew Kale Miso Slaw Extra Side", channel: 'deliveroo', hour: 12, items: 3, net: 13.5 },
  { category: "Individual Portion", code: "98663", name: "Cashew Kale Miso Slaw Extra Side", channel: 'instore', hour: 12, items: 2, net: 6.42 },
  { category: "Individual Portion", code: "98656", name: "Cauliflower Extra Side", channel: 'deliveroo', hour: 12, items: 1, net: 3.75 },
  { category: "Individual Portion", code: "1003587", name: "Chickpea + Pickles Extra Side", channel: 'deliveroo', hour: 12, items: 2, net: 13.5 },
  { category: "Individual Portion", code: "1003587", name: "Chickpea + Pickles Extra Side", channel: 'instore', hour: 12, items: 1, net: 2.92 },
  { category: "Individual Portion", code: "1001518", name: "Harissa Chicken Extra Main", channel: 'deliveroo', hour: 12, items: 1, net: 6.67 },
  { category: "Individual Portion", code: "1001050", name: "Mac & Cheese Extra Side", channel: 'deliveroo', hour: 12, items: 2, net: 10 },
  { category: "Individual Portion", code: "1003744", name: "Spring Feta Caesar Extra Side", channel: 'instore', hour: 12, items: 1, net: 2.92 },
  { category: "Individual Portion", code: "98658", name: "Sweet Potato Extra Side", channel: 'deliveroo', hour: 12, items: 1, net: 3.75 },
  { category: "Individual Portion", code: "98658", name: "Sweet Potato Extra Side", channel: 'instore', hour: 12, items: 1, net: 2.92 },
  { category: "Individual Portion", code: "1002886", name: "Tofu Extra Main", channel: 'instore', hour: 12, items: 1, net: 4.17 },
  { category: "Set Fieldtrays", code: "1002194", name: "Butcher`s Cut", channel: 'deliveroo', hour: 12, items: 2, net: 26.58 },
  { category: "Set Fieldtrays", code: "1002196", name: "Farmer`s Catch", channel: 'deliveroo', hour: 12, items: 1, net: 13.96 },
  { category: "Set Fieldtrays", code: "1002193", name: "J`s Classic", channel: 'deliveroo', hour: 12, items: 1, net: 11.63 },
  { category: "Set Fieldtrays", code: "1002193", name: "J`s Classic", channel: 'kiosk', hour: 12, items: 2, net: 18.26 },
  { category: "Set Fieldtrays", code: "1003764", name: "The Amba", channel: 'deliveroo', hour: 12, items: 1, net: 11.63 },
  { category: "Set Fieldtrays", code: "1003764", name: "The Amba", channel: 'kiosk', hour: 12, items: 2, net: 18.26 },
  { category: "Set Fieldtrays", code: "1002197", name: "Where My Vegans At?", channel: 'deliveroo', hour: 12, items: 1, net: 11.63 },
  { category: "Snacks/Impluse", code: "1001843", name: "Almond Bakewell Flapjack", channel: 'instore', hour: 12, items: 4, net: 7.91 },
  { category: "Snacks/Impluse", code: "1001445", name: "Banana Bread", channel: 'instore', hour: 12, items: 2, net: 4.9 },
  { category: "Snacks/Impluse", code: "1001449", name: "Brownies", channel: 'instore', hour: 12, items: 1, net: 2.92 },
  { category: "Snacks/Impluse", code: "1000969", name: "Chocolate Chip Cookie", channel: 'instore', hour: 12, items: 9, net: 16.13 },
  { category: "Snacks/Impluse", code: "1000969", name: "Chocolate Chip Cookie", channel: 'kiosk', hour: 12, items: 1, net: 1.95 },
  { category: "Snacks/Impluse", code: "1000971", name: "Matcha Cookie", channel: 'instore', hour: 12, items: 10, net: 17.63 },
  { category: "Snacks/Impluse", code: "1000971", name: "Matcha Cookie", channel: 'kiosk', hour: 12, items: 1, net: 1.95 },
  { category: "Snacks/Impluse", code: "1003611", name: "Oat Cranberry Cookie", channel: 'instore', hour: 12, items: 1, net: 1.95 },
  { category: "Snacks/Impluse", code: "1003611", name: "Oat Cranberry Cookie", channel: 'kiosk', hour: 12, items: 1, net: 1.56 },
  { category: "Snacks/Impluse", code: "1002447", name: "Pitta Chips Rosemary", channel: 'instore', hour: 12, items: 1, net: 1.46 },
  { category: "Tea Options", code: "103115", name: "English Breakfast", channel: 'instore', hour: 12, items: 2, net: 0 },
  { category: "Toppings", code: "1003808", name: "Pickled Cucumber", channel: 'instore', hour: 12, items: 1, net: 0.5 },
  { category: "Alcohol", code: "1002849", name: "Pale Ale", channel: 'instore', hour: 13, items: 1, net: 3.71 },
  { category: "Coffee Milks", code: "1000993", name: "ALMOND", channel: 'instore', hour: 13, items: 2, net: 0.84 },
  { category: "Coffee Milks", code: "1000997", name: "OAT", channel: 'instore', hour: 13, items: 1, net: 0.42 },
  { category: "Coffee Milks", code: "103069", name: "OAT", channel: 'instore', hour: 13, items: 1, net: 0 },
  { category: "Cold Drinks", code: "1003610", name: "Agua De Madre - Passion Fruit", channel: 'instore', hour: 13, items: 2, net: 6.26 },
  { category: "Cold Drinks", code: "1003118", name: "Agua De Madre - Pink Grapefruit", channel: 'instore', hour: 13, items: 2, net: 6.26 },
  { category: "Cold Drinks", code: "103118", name: "Coke", channel: 'instore', hour: 13, items: 1, net: 1.25 },
  { category: "Cold Drinks", code: "103118", name: "Coke", channel: 'kiosk', hour: 13, items: 1, net: 1.25 },
  { category: "Cold Drinks", code: "1002627", name: "Dash Peach", channel: 'instore', hour: 13, items: 5, net: 9.77 },
  { category: "Cold Drinks", code: "103119", name: "Diet Coke", channel: 'instore', hour: 13, items: 9, net: 11.25 },
  { category: "Cold Drinks", code: "1000977", name: "Farmers Lemonade", channel: 'instore', hour: 13, items: 5, net: 9.8 },
  { category: "Cold Drinks", code: "1000977", name: "Farmers Lemonade", channel: 'kiosk', hour: 13, items: 1, net: 1.96 },
  { category: "Cold Drinks", code: "103136", name: "Passion Fruit- JARR", channel: 'instore', hour: 13, items: 2, net: 9.87 },
  { category: "Cold Drinks", code: "1001867", name: "Pink Lemonade", channel: 'deliveroo', hour: 13, items: 1, net: 2.71 },
  { category: "Cold Drinks", code: "1001867", name: "Pink Lemonade", channel: 'instore', hour: 13, items: 2, net: 4.26 },
  { category: "Cold Drinks", code: "103123", name: "Sparkling Water", channel: 'instore', hour: 13, items: 6, net: 8.75 },
  { category: "Cold Drinks", code: "103122", name: "Still Water", channel: 'instore', hour: 13, items: 3, net: 3.75 },
  { category: "Cold Drinks", code: "1001982", name: "TRIP - Peach Ginger", channel: 'instore', hour: 13, items: 2, net: 5.42 },
  { category: "Field Trays", code: "1003748", name: "Amba Chicken Fieldtray Main", channel: 'deliveroo', hour: 13, items: 2, net: 23.26 },
  { category: "Field Trays", code: "1003748", name: "Amba Chicken Fieldtray Main", channel: 'instore', hour: 13, items: 50, net: 447.35 },
  { category: "Field Trays", code: "1003748", name: "Amba Chicken Fieldtray Main", channel: 'kiosk', hour: 13, items: 3, net: 27.39 },
  { category: "Field Trays", code: "1001583", name: "Broccoli Fieldtray Main", channel: 'instore', hour: 13, items: 1, net: 7.71 },
  { category: "Field Trays", code: "1001584", name: "Cauliflower Fieldtray Main", channel: 'instore', hour: 13, items: 2, net: 15.42 },
  { category: "Field Trays", code: "1001747", name: "Harissa Chicken Fieldtray Main", channel: 'clickcollect', hour: 13, items: 1, net: 9.13 },
  { category: "Field Trays", code: "1001747", name: "Harissa Chicken Fieldtray Main", channel: 'deliveroo', hour: 13, items: 1, net: 11.63 },
  { category: "Field Trays", code: "1001747", name: "Harissa Chicken Fieldtray Main", channel: 'instore', hour: 13, items: 35, net: 317.72 },
  { category: "Field Trays", code: "1001747", name: "Harissa Chicken Fieldtray Main", channel: 'kiosk', hour: 13, items: 10, net: 91.3 },
  { category: "Field Trays", code: "1001748", name: "Mac & Cheese Fieldtray Main", channel: 'instore', hour: 13, items: 1, net: 7.71 },
  { category: "Field Trays", code: "1001798", name: "Salmon Fieldtray Main", channel: 'deliveroo', hour: 13, items: 1, net: 13.96 },
  { category: "Field Trays", code: "1001798", name: "Salmon Fieldtray Main", channel: 'instore', hour: 13, items: 20, net: 210.4 },
  { category: "Field Trays", code: "1001750", name: "Steak Fieldtray Main", channel: 'deliveroo', hour: 13, items: 6, net: 79.74 },
  { category: "Field Trays", code: "1001750", name: "Steak Fieldtray Main", channel: 'instore', hour: 13, items: 9, net: 93.54 },
  { category: "Field Trays", code: "1001750", name: "Steak Fieldtray Main", channel: 'kiosk', hour: 13, items: 3, net: 31.89 },
  { category: "Field Trays", code: "1002885", name: "Tofu Fieldtray Main", channel: 'instore', hour: 13, items: 10, net: 91.3 },
  { category: "Field Trays", code: "1002885", name: "Tofu Fieldtray Main", channel: 'kiosk', hour: 13, items: 1, net: 9.13 },
  { category: "Fieldbowls", code: "1003760", name: "The Amba Bowl", channel: 'instore', hour: 13, items: 6, net: 44.76 },
  { category: "Fieldbowls", code: "1003761", name: "The Harissa Bowl", channel: 'clickcollect', hour: 13, items: 1, net: 7.46 },
  { category: "Fieldbowls", code: "1003761", name: "The Harissa Bowl", channel: 'instore', hour: 13, items: 13, net: 104.44 },
  { category: "Fieldbowls", code: "1003761", name: "The Harissa Bowl", channel: 'kiosk', hour: 13, items: 2, net: 14.92 },
  { category: "Fieldbowls", code: "1003762", name: "The Salmon Bowl", channel: 'instore', hour: 13, items: 6, net: 75.53 },
  { category: "Fieldbowls", code: "1003763", name: "The Tofu Bowl", channel: 'instore', hour: 13, items: 2, net: 14.92 },
  { category: "FT Extras", code: "1000974", name: "Avocado", channel: 'instore', hour: 13, items: 2, net: 4 },
  { category: "FT Extras", code: "1000974", name: "Avocado", channel: 'kiosk', hour: 13, items: 1, net: 2 },
  { category: "FT Extras", code: "1000976", name: "Egg", channel: 'deliveroo', hour: 13, items: 1, net: 1 },
  { category: "FT Extras", code: "1000976", name: "Egg", channel: 'instore', hour: 13, items: 2, net: 1.38 },
  { category: "FT Extras", code: "1003766", name: "Pickled Cucumber", channel: 'instore', hour: 13, items: 1, net: 0.5 },
  { category: "FT Extras", code: "1003767", name: "Pickled Onion", channel: 'deliveroo', hour: 13, items: 1, net: 0.75 },
  { category: "FT Extras", code: "1003767", name: "Pickled Onion", channel: 'instore', hour: 13, items: 1, net: 0.5 },
  { category: "FT Extras", code: "1003765", name: "Sesame Cucumber", channel: 'instore', hour: 13, items: 1, net: 0.5 },
  { category: "FT Extras", code: "1003765", name: "Sesame Cucumber", channel: 'kiosk', hour: 13, items: 1, net: 0.5 },
  { category: "FT Grains", code: "98680", name: "Farmer's Grains", channel: 'deliveroo', hour: 13, items: 2, net: 0 },
  { category: "FT Grains", code: "98680", name: "Farmer's Grains", channel: 'instore', hour: 13, items: 18, net: 0 },
  { category: "FT Grains", code: "98680", name: "Farmer's Grains", channel: 'kiosk', hour: 13, items: 9, net: 0 },
  { category: "FT Grains", code: "98679", name: "Rice", channel: 'deliveroo', hour: 13, items: 6, net: 0 },
  { category: "FT Grains", code: "98679", name: "Rice", channel: 'instore', hour: 13, items: 81, net: 0 },
  { category: "FT Grains", code: "98679", name: "Rice", channel: 'kiosk', hour: 13, items: 5, net: 0 },
  { category: "FT Grains", code: "1003740", name: "Sesame Cabbage", channel: 'clickcollect', hour: 13, items: 1, net: 0 },
  { category: "FT Grains", code: "1003740", name: "Sesame Cabbage", channel: 'deliveroo', hour: 13, items: 2, net: 0 },
  { category: "FT Grains", code: "1003740", name: "Sesame Cabbage", channel: 'instore', hour: 13, items: 9, net: 0 },
  { category: "FT Grains", code: "1003740", name: "Sesame Cabbage", channel: 'kiosk', hour: 13, items: 3, net: 0 },
  { category: "FT Grains", code: "98681", name: "Spinach", channel: 'instore', hour: 13, items: 20, net: 0 },
  { category: "FT Sauces", code: "102976", name: "Chimichurri", channel: 'clickcollect', hour: 13, items: 1, net: 0.5 },
  { category: "FT Sauces", code: "102976", name: "Chimichurri", channel: 'deliveroo', hour: 13, items: 6, net: 4.5 },
  { category: "FT Sauces", code: "102976", name: "Chimichurri", channel: 'instore', hour: 13, items: 3, net: 1.65 },
  { category: "FT Sauces", code: "1000961", name: "Chimichurri", channel: 'instore', hour: 13, items: 3, net: 1.42 },
  { category: "FT Sauces", code: "102976", name: "Chimichurri", channel: 'kiosk', hour: 13, items: 6, net: 3 },
  { category: "FT Sauces", code: "102977", name: "Green Tahini", channel: 'instore', hour: 13, items: 6, net: 2.75 },
  { category: "FT Sauces", code: "1000964", name: "Green Tahini", channel: 'instore', hour: 13, items: 3, net: 1.92 },
  { category: "FT Sauces", code: "102977", name: "Green Tahini", channel: 'kiosk', hour: 13, items: 2, net: 1 },
  { category: "FT Sauces", code: "1001974", name: "J’s Aioli", channel: 'deliveroo', hour: 13, items: 1, net: 0.75 },
  { category: "FT Sauces", code: "1001981", name: "J’s Aioli", channel: 'deliveroo', hour: 13, items: 1, net: 0.75 },
  { category: "FT Sauces", code: "1001974", name: "J’s Aioli", channel: 'instore', hour: 13, items: 2, net: 1.33 },
  { category: "FT Sauces", code: "1001981", name: "J’s Aioli", channel: 'instore', hour: 13, items: 5, net: 2.14 },
  { category: "FT Sauces", code: "1001981", name: "J’s Aioli", channel: 'kiosk', hour: 13, items: 4, net: 2 },
  { category: "FT Sauces", code: "1001067", name: "No Sauce", channel: 'deliveroo', hour: 13, items: 6, net: 0 },
  { category: "FT Sauces", code: "1001067", name: "No Sauce", channel: 'instore', hour: 13, items: 128, net: 0 },
  { category: "FT Sauces", code: "1001067", name: "No Sauce", channel: 'kiosk', hour: 13, items: 6, net: 0 },
  { category: "FT Sauces", code: "102975", name: "Red Pepper", channel: 'instore', hour: 13, items: 3, net: 1.42 },
  { category: "FT Sauces", code: "1000963", name: "Red Pepper", channel: 'instore', hour: 13, items: 1, net: 0.42 },
  { category: "FT Sauces", code: "102975", name: "Red Pepper", channel: 'kiosk', hour: 13, items: 2, net: 1 },
  { category: "FT Sides", code: "98670", name: "Broccoli", channel: 'deliveroo', hour: 13, items: 4, net: 0 },
  { category: "FT Sides", code: "98670", name: "Broccoli", channel: 'instore', hour: 13, items: 27, net: 0 },
  { category: "FT Sides", code: "98670", name: "Broccoli", channel: 'kiosk', hour: 13, items: 6, net: 0 },
  { category: "FT Sides", code: "98668", name: "Cashew Kale Miso Slaw", channel: 'deliveroo', hour: 13, items: 1, net: 0 },
  { category: "FT Sides", code: "98668", name: "Cashew Kale Miso Slaw", channel: 'instore', hour: 13, items: 26, net: 0 },
  { category: "FT Sides", code: "98668", name: "Cashew Kale Miso Slaw", channel: 'kiosk', hour: 13, items: 6, net: 0 },
  { category: "FT Sides", code: "98690", name: "Cauliflower", channel: 'deliveroo', hour: 13, items: 5, net: 0 },
  { category: "FT Sides", code: "98690", name: "Cauliflower", channel: 'instore', hour: 13, items: 41, net: 0 },
  { category: "FT Sides", code: "1003583", name: "Chickpea + Pickles", channel: 'instore', hour: 13, items: 23, net: 0 },
  { category: "FT Sides", code: "1003583", name: "Chickpea + Pickles", channel: 'kiosk', hour: 13, items: 3, net: 0 },
  { category: "FT Sides", code: "1003742", name: "IOW Tomato", channel: 'instore', hour: 13, items: 17, net: 0 },
  { category: "FT Sides", code: "1003742", name: "IOW Tomato", channel: 'kiosk', hour: 13, items: 3, net: 0 },
  { category: "FT Sides", code: "1001060", name: "Mac & Cheese", channel: 'clickcollect', hour: 13, items: 1, net: 0 },
  { category: "FT Sides", code: "1001060", name: "Mac & Cheese", channel: 'deliveroo', hour: 13, items: 3, net: 0 },
  { category: "FT Sides", code: "1001060", name: "Mac & Cheese", channel: 'instore', hour: 13, items: 42, net: 0 },
  { category: "FT Sides", code: "1001060", name: "Mac & Cheese", channel: 'kiosk', hour: 13, items: 8, net: 0 },
  { category: "FT Sides", code: "1003743", name: "Parmesan Potatoes", channel: 'deliveroo', hour: 13, items: 1, net: 0 },
  { category: "FT Sides", code: "1003743", name: "Parmesan Potatoes", channel: 'instore', hour: 13, items: 28, net: 0 },
  { category: "FT Sides", code: "1003743", name: "Parmesan Potatoes", channel: 'kiosk', hour: 13, items: 1, net: 0 },
  { category: "FT Sides", code: "1003741", name: "Spring Feta Caesar", channel: 'clickcollect', hour: 13, items: 1, net: 0 },
  { category: "FT Sides", code: "1003741", name: "Spring Feta Caesar", channel: 'deliveroo', hour: 13, items: 2, net: 0 },
  { category: "FT Sides", code: "1003741", name: "Spring Feta Caesar", channel: 'instore', hour: 13, items: 19, net: 0 },
  { category: "FT Sides", code: "1003741", name: "Spring Feta Caesar", channel: 'kiosk', hour: 13, items: 4, net: 0 },
  { category: "FT Sides", code: "98692", name: "Sweet Potato", channel: 'deliveroo', hour: 13, items: 4, net: 0 },
  { category: "FT Sides", code: "98692", name: "Sweet Potato", channel: 'instore', hour: 13, items: 30, net: 0 },
  { category: "FT Sides", code: "98692", name: "Sweet Potato", channel: 'kiosk', hour: 13, items: 3, net: 0 },
  { category: "Hot Drinks", code: "103054", name: "Americano", channel: 'instore', hour: 13, items: 1, net: 2.5 },
  { category: "Hot Drinks", code: "103055", name: "Cappuccino", channel: 'instore', hour: 13, items: 1, net: 2.92 },
  { category: "Hot Drinks", code: "103062", name: "Hot Chocolate", channel: 'instore', hour: 13, items: 1, net: 3.29 },
  { category: "Hot Drinks", code: "1002954", name: "Tahini Latte", channel: 'instore', hour: 13, items: 1, net: 3.95 },
  { category: "Hot Drinks", code: "103063", name: "Teas", channel: 'instore', hour: 13, items: 1, net: 1.67 },
  { category: "Individual Portion", code: "98663", name: "Cashew Kale Miso Slaw Extra Side", channel: 'deliveroo', hour: 13, items: 2, net: 9 },
  { category: "Individual Portion", code: "98663", name: "Cashew Kale Miso Slaw Extra Side", channel: 'instore', hour: 13, items: 4, net: 12.14 },
  { category: "Individual Portion", code: "1001518", name: "Harissa Chicken Extra Main", channel: 'deliveroo', hour: 13, items: 1, net: 6.67 },
  { category: "Individual Portion", code: "1003745", name: "IOW Tomatoes Extra Side", channel: 'instore', hour: 13, items: 2, net: 6.3 },
  { category: "Individual Portion", code: "1001050", name: "Mac & Cheese Extra Side", channel: 'deliveroo', hour: 13, items: 1, net: 5 },
  { category: "Individual Portion", code: "1001050", name: "Mac & Cheese Extra Side", channel: 'instore', hour: 13, items: 1, net: 2.67 },
  { category: "Individual Portion", code: "1003744", name: "Spring Feta Caesar Extra Side", channel: 'instore', hour: 13, items: 3, net: 9.34 },
  { category: "Individual Portion", code: "98650", name: "Steak Extra Main", channel: 'instore', hour: 13, items: 1, net: 4.67 },
  { category: "Individual Portion", code: "98658", name: "Sweet Potato Extra Side", channel: 'instore', hour: 13, items: 1, net: 2.92 },
  { category: "Set Fieldtrays", code: "1002194", name: "Butcher`s Cut", channel: 'deliveroo', hour: 13, items: 1, net: 13.29 },
  { category: "Set Fieldtrays", code: "1002193", name: "J`s Classic", channel: 'deliveroo', hour: 13, items: 1, net: 11.63 },
  { category: "Set Fieldtrays", code: "1002193", name: "J`s Classic", channel: 'kiosk', hour: 13, items: 2, net: 18.26 },
  { category: "Set Fieldtrays", code: "1003764", name: "The Amba", channel: 'deliveroo', hour: 13, items: 1, net: 11.63 },
  { category: "Set Fieldtrays", code: "1003764", name: "The Amba", channel: 'kiosk', hour: 13, items: 1, net: 9.13 },
  { category: "Snacks/Impluse", code: "1001843", name: "Almond Bakewell Flapjack", channel: 'instore', hour: 13, items: 3, net: 6.24 },
  { category: "Snacks/Impluse", code: "1003690", name: "Apple Crumble Cupcake", channel: 'instore', hour: 13, items: 5, net: 19.33 },
  { category: "Snacks/Impluse", code: "1001445", name: "Banana Bread", channel: 'instore', hour: 13, items: 2, net: 9 },
  { category: "Snacks/Impluse", code: "1001449", name: "Brownies", channel: 'instore', hour: 13, items: 1, net: 3.5 },
  { category: "Snacks/Impluse", code: "1002023", name: "Cheese & Onion - Crisp", channel: 'instore', hour: 13, items: 1, net: 1.08 },
  { category: "Snacks/Impluse", code: "1000969", name: "Chocolate Chip Cookie", channel: 'instore', hour: 13, items: 8, net: 15.88 },
  { category: "Snacks/Impluse", code: "1000969", name: "Chocolate Chip Cookie", channel: 'kiosk', hour: 13, items: 1, net: 1.95 },
  { category: "Snacks/Impluse", code: "1002665", name: "Chocolate Maple Banana Cupcake", channel: 'deliveroo', hour: 13, items: 2, net: 10 },
  { category: "Snacks/Impluse", code: "1002665", name: "Chocolate Maple Banana Cupcake", channel: 'instore', hour: 13, items: 6, net: 26.66 },
  { category: "Snacks/Impluse", code: "1002021", name: "Lightly Salted - Crisps", channel: 'instore', hour: 13, items: 1, net: 1.08 },
  { category: "Snacks/Impluse", code: "1000971", name: "Matcha Cookie", channel: 'instore', hour: 13, items: 5, net: 9.43 },
  { category: "Snacks/Impluse", code: "1003611", name: "Oat Cranberry Cookie", channel: 'instore', hour: 13, items: 3, net: 5.21 },
  { category: "Snacks/Impluse", code: "1003670", name: "Pecan Flourless Brownie Bites", channel: 'instore', hour: 13, items: 1, net: 7.95 },
  { category: "Snacks/Impluse", code: "1002440", name: "Tonys Choc Caramel", channel: 'instore', hour: 13, items: 1, net: 1.63 },
  { category: "Tea Options", code: "103116", name: "Green Tea", channel: 'instore', hour: 13, items: 1, net: 0 },
  { category: "Coffee Milks", code: "103072", name: "BLACK", channel: 'instore', hour: 14, items: 1, net: 0 },
  { category: "Coffee Milks", code: "103077", name: "FULL FAT", channel: 'instore', hour: 14, items: 1, net: 0 },
  { category: "Coffee Milks", code: "1000996", name: "FULL FAT", channel: 'instore', hour: 14, items: 2, net: 0 },
  { category: "Coffee Milks", code: "1002508", name: "FULL FAT", channel: 'instore', hour: 14, items: 1, net: 0 },
  { category: "Coffee Milks", code: "1000997", name: "OAT", channel: 'instore', hour: 14, items: 1, net: 0.42 },
  { category: "Coffee Syrup", code: "1002949", name: "Salted Caramel", channel: 'instore', hour: 14, items: 1, net: 0.5 },
  { category: "Cold Drinks", code: "1003610", name: "Agua De Madre - Passion Fruit", channel: 'instore', hour: 14, items: 2, net: 6.26 },
  { category: "Cold Drinks", code: "1003118", name: "Agua De Madre - Pink Grapefruit", channel: 'instore', hour: 14, items: 1, net: 3.13 },
  { category: "Cold Drinks", code: "1002531", name: "Apple Juice", channel: 'instore', hour: 14, items: 2, net: 5.42 },
  { category: "Cold Drinks", code: "1002627", name: "Dash Peach", channel: 'instore', hour: 14, items: 2, net: 3.26 },
  { category: "Cold Drinks", code: "103119", name: "Diet Coke", channel: 'instore', hour: 14, items: 1, net: 1.25 },
  { category: "Cold Drinks", code: "1000977", name: "Farmers Lemonade", channel: 'instore', hour: 14, items: 2, net: 3.92 },
  { category: "Cold Drinks", code: "1002085", name: "Orange Juice", channel: 'instore', hour: 14, items: 2, net: 5.42 },
  { category: "Cold Drinks", code: "103123", name: "Sparkling Water", channel: 'instore', hour: 14, items: 1, net: 1.25 },
  { category: "Cold Drinks", code: "103122", name: "Still Water", channel: 'instore', hour: 14, items: 5, net: 6.25 },
  { category: "Cold Drinks", code: "1001982", name: "TRIP - Peach Ginger", channel: 'instore', hour: 14, items: 1, net: 2.71 },
  { category: "Field Trays", code: "1003748", name: "Amba Chicken Fieldtray Main", channel: 'instore', hour: 14, items: 15, net: 135.12 },
  { category: "Field Trays", code: "1001747", name: "Harissa Chicken Fieldtray Main", channel: 'instore', hour: 14, items: 15, net: 133.29 },
  { category: "Field Trays", code: "1001798", name: "Salmon Fieldtray Main", channel: 'instore', hour: 14, items: 15, net: 157.53 },
  { category: "Field Trays", code: "1001750", name: "Steak Fieldtray Main", channel: 'instore', hour: 14, items: 6, net: 63.78 },
  { category: "Field Trays", code: "1002885", name: "Tofu Fieldtray Main", channel: 'instore', hour: 14, items: 4, net: 36.52 },
  { category: "Fieldbowls", code: "1003760", name: "The Amba Bowl", channel: 'instore', hour: 14, items: 3, net: 22.38 },
  { category: "Fieldbowls", code: "1003761", name: "The Harissa Bowl", channel: 'instore', hour: 14, items: 5, net: 37.3 },
  { category: "FT Extras", code: "1000974", name: "Avocado", channel: 'instore', hour: 14, items: 3, net: 6 },
  { category: "FT Extras", code: "1000976", name: "Egg", channel: 'instore', hour: 14, items: 2, net: 1.38 },
  { category: "FT Grains", code: "98680", name: "Farmer's Grains", channel: 'instore', hour: 14, items: 15, net: 0 },
  { category: "FT Grains", code: "98679", name: "Rice", channel: 'instore', hour: 14, items: 36, net: 0 },
  { category: "FT Grains", code: "98681", name: "Spinach", channel: 'instore', hour: 14, items: 4, net: 0 },
  { category: "FT Sauces", code: "1000961", name: "Chimichurri", channel: 'instore', hour: 14, items: 1, net: 0.42 },
  { category: "FT Sauces", code: "102976", name: "Chimichurri", channel: 'instore', hour: 14, items: 3, net: 1.42 },
  { category: "FT Sauces", code: "102977", name: "Green Tahini", channel: 'instore', hour: 14, items: 3, net: 1.34 },
  { category: "FT Sauces", code: "1001974", name: "J’s Aioli", channel: 'instore', hour: 14, items: 2, net: 0.92 },
  { category: "FT Sauces", code: "1001981", name: "J’s Aioli", channel: 'instore', hour: 14, items: 2, net: 1 },
  { category: "FT Sauces", code: "1001067", name: "No Sauce", channel: 'instore', hour: 14, items: 55, net: 0 },
  { category: "FT Sauces", code: "102975", name: "Red Pepper", channel: 'instore', hour: 14, items: 5, net: 2.17 },
  { category: "FT Sides", code: "98670", name: "Broccoli", channel: 'instore', hour: 14, items: 20, net: 0 },
  { category: "FT Sides", code: "98668", name: "Cashew Kale Miso Slaw", channel: 'instore', hour: 14, items: 5, net: 0 },
  { category: "FT Sides", code: "98690", name: "Cauliflower", channel: 'instore', hour: 14, items: 13, net: 0 },
  { category: "FT Sides", code: "1003583", name: "Chickpea + Pickles", channel: 'instore', hour: 14, items: 7, net: 0 },
  { category: "FT Sides", code: "1003742", name: "IOW Tomato", channel: 'instore', hour: 14, items: 9, net: 0 },
  { category: "FT Sides", code: "1001060", name: "Mac & Cheese", channel: 'instore', hour: 14, items: 11, net: 0 },
  { category: "FT Sides", code: "1003743", name: "Parmesan Potatoes", channel: 'instore', hour: 14, items: 6, net: 0 },
  { category: "FT Sides", code: "1003741", name: "Spring Feta Caesar", channel: 'instore', hour: 14, items: 13, net: 0 },
  { category: "FT Sides", code: "98692", name: "Sweet Potato", channel: 'instore', hour: 14, items: 26, net: 0 },
  { category: "Hot Drinks", code: "103054", name: "Americano", channel: 'instore', hour: 14, items: 1, net: 2.5 },
  { category: "Hot Drinks", code: "103065", name: "Chai Latte", channel: 'instore', hour: 14, items: 2, net: 6.58 },
  { category: "Hot Drinks", code: "1003620", name: "Chilli Hot Chocolate", channel: 'instore', hour: 14, items: 1, net: 4.25 },
  { category: "Hot Drinks", code: "103081", name: "Espresso", channel: 'instore', hour: 14, items: 4, net: 8.32 },
  { category: "Hot Drinks", code: "103053", name: "Flat White", channel: 'instore', hour: 14, items: 1, net: 2.83 },
  { category: "Hot Drinks", code: "103061", name: "Ice Milk Coffee", channel: 'instore', hour: 14, items: 1, net: 2.92 },
  { category: "Individual Portion", code: "1003747", name: "Amba Chicken Extra Main", channel: 'instore', hour: 14, items: 1, net: 4.17 },
  { category: "Individual Portion", code: "98655", name: "Broccoli Extra Side", channel: 'instore', hour: 14, items: 2, net: 5.84 },
  { category: "Individual Portion", code: "1003587", name: "Chickpea + Pickles Extra Side", channel: 'instore', hour: 14, items: 1, net: 3.5 },
  { category: "Individual Portion", code: "1001050", name: "Mac & Cheese Extra Side", channel: 'instore', hour: 14, items: 1, net: 3.33 },
  { category: "Individual Portion", code: "98658", name: "Sweet Potato Extra Side", channel: 'instore', hour: 14, items: 1, net: 2.92 },
  { category: "Snacks/Impluse", code: "1001843", name: "Almond Bakewell Flapjack", channel: 'instore', hour: 14, items: 1, net: 2.08 },
  { category: "Snacks/Impluse", code: "1001445", name: "Banana Bread", channel: 'instore', hour: 14, items: 1, net: 3 },
  { category: "Snacks/Impluse", code: "1001449", name: "Brownies", channel: 'instore', hour: 14, items: 1, net: 3.5 },
  { category: "Snacks/Impluse", code: "1000969", name: "Chocolate Chip Cookie", channel: 'instore', hour: 14, items: 4, net: 6.84 },
  { category: "Snacks/Impluse", code: "1000971", name: "Matcha Cookie", channel: 'instore', hour: 14, items: 3, net: 5.53 },
  { category: "Snacks/Impluse", code: "1003611", name: "Oat Cranberry Cookie", channel: 'instore', hour: 14, items: 2, net: 3.58 },
  { category: "Snacks/Impluse", code: "1002447", name: "Pitta Chips Rosemary", channel: 'instore', hour: 14, items: 2, net: 2.92 },
  { category: "Toppings", code: "1003808", name: "Pickled Cucumber", channel: 'instore', hour: 14, items: 1, net: 0.5 },
];
